ALTER TABLE `admins` ADD `role` text DEFAULT 'admin' NOT NULL;
--> statement-breakpoint
INSERT INTO workspace_records(id,scope,kind,data,created_at,updated_at) SELECT lower(hex(randomblob(16))),id,'blog','{"title":"Before your first project conversation","slug":"before-your-first-project-conversation","category":"Planning","excerpt":"A little preparation can make your first conversation clearer and more useful.","body":"Start with what you want to accomplish. Write down what you have noticed, which areas concern you, and the result you would like to achieve. You do not need to diagnose the problem before asking for help.\n\nGather any photos you can take safely from the ground, existing project paperwork, and questions about timing or access. Avoid putting yourself at risk to collect more information.\n\nDuring the conversation, ask what the next step involves, what information is still needed, and how you will receive the proposed scope. Keep notes so you can compare options and follow up on unanswered questions.\n\nThis is a general planning guide. Recommendations for a specific property depend on an assessment and the agreed scope.","coverPhotoId":""}',strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM tenants WHERE slug='robles-roofing' AND NOT EXISTS(SELECT 1 FROM workspace_records WHERE scope=tenants.id AND kind='blog' AND json_extract(data,'$.slug')='before-your-first-project-conversation');

--> statement-breakpoint
INSERT INTO workspace_records(id,scope,kind,data,created_at,updated_at) SELECT lower(hex(randomblob(16))),id,'blog','{"title":"Questions to ask when reviewing an estimate","slug":"questions-to-ask-when-reviewing-an-estimate","category":"Estimates","excerpt":"Look beyond the total and understand what is included in the proposed work.","body":"An estimate is easier to discuss when the scope is clear. Ask which areas, materials, preparation, and cleanup are included. If something matters to you, make sure it is addressed in the written scope.\n\nDiscuss the proposed timeline and what could affect it. Ask how changes or newly discovered conditions would be documented and approved before additional work proceeds.\n\nIf you are comparing proposals, compare the descriptions of the work as well as the totals. Note any unanswered questions and request clarification before making a decision.\n\nKeep the estimate and related correspondence together. These documents help everyone stay aligned on the agreed next steps.","coverPhotoId":""}',strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM tenants WHERE slug='robles-roofing' AND NOT EXISTS(SELECT 1 FROM workspace_records WHERE scope=tenants.id AND kind='blog' AND json_extract(data,'$.slug')='questions-to-ask-when-reviewing-an-estimate');

--> statement-breakpoint
INSERT INTO workspace_records(id,scope,kind,data,created_at,updated_at) SELECT lower(hex(randomblob(16))),id,'blog','{"title":"Keep a simple record of your property projects","slug":"keep-a-record-of-your-property-projects","category":"Maintenance","excerpt":"Organized photos and paperwork make future project conversations easier.","body":"Keep a folder for each property project. Save the agreed scope, invoices, material information, and any care instructions you receive. Label photos with the date and the part of the property they show.\n\nAfter the work, note any follow-up items and the person to contact with questions. When written care instructions are supplied, keep them with the project records rather than relying on memory.\n\nIf you notice a change later, document what you can observe safely and contact an appropriate professional. A clear record can help explain what changed and when it was first noticed.\n\nThis guide concerns organization and communication; it does not replace property-specific inspection or maintenance advice.","coverPhotoId":""}',strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM tenants WHERE slug='robles-roofing' AND NOT EXISTS(SELECT 1 FROM workspace_records WHERE scope=tenants.id AND kind='blog' AND json_extract(data,'$.slug')='keep-a-record-of-your-property-projects');
