import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {worker,env,admin} from './preview-fixture.mjs';
import {localMorning} from '../src/control.js';
const origin='https://test.local';
async function req(path,method='GET',data,user=admin){return worker.fetch(new Request(origin+'/api'+path,{method,headers:{origin,'content-type':data instanceof Uint8Array?'image/jpeg':'application/json',...(user?{'oai-authenticated-user-id':user.id,'oai-authenticated-user-email':user.email}:{})},body:data instanceof Uint8Array?data:data?JSON.stringify(data):undefined}),env)}
async function api(path,method='GET',data,user=admin){const r=await req(path,method,data,user);assert.equal(r.status,200,await r.clone().text());return r.json()}
assert.equal(localMorning('2027-07-06T22:00:00Z','America/Los_Angeles',9),'2027-07-06T16:00:00.000Z');assert.equal(localMorning('2027-01-05T23:00:00Z','America/Los_Angeles',9),'2027-01-05T17:00:00.000Z');
let profile=await api('/control/profile');await api('/control/profile','PUT',{version:profile.record.version,data:{displayName:'Yoel Test',title:'Founder',phone:'2025550100',timezone:'America/Los_Angeles',bio:'Test profile'}});await api('/control/profile-photo','POST',new Uint8Array(readFileSync('./public/assets/roofing.jpg')));profile=await api('/control/profile');assert.ok(profile.record.data.photoKey);assert.equal((await req('/control/avatar/'+admin.id)).status,200);assert.equal((await req('/control/avatar/'+admin.id,'GET',null,null)).status,401);assert.equal((await api('/crm/global/members')).members[0].displayName,'Yoel Test');await api('/control/profile-photo','DELETE',{});assert.equal((await req('/control/avatar/'+admin.id)).status,404);
const s=await api('/control/settings');assert.ok(s.connections.some(c=>c.id==='klarna'&&c.status.includes('B2B')));assert.equal((await req('/control/settings','PUT',{version:s.record.version,data:{...s.record.data,monthlyPayments:0}})).status,400);
const {id}=await api('/workspace/global/contacts','POST',{data:{name:'John Test',company:'John Roofing',email:'john@example.test',phone:'2025550101',appointmentEmailConsent:true,appointmentSmsConsent:true}});
const a=await api('/workspace/global/calendar','POST',{data:{title:'Website demo',contactId:id,start:'2027-07-06T22:00:00Z',end:'2027-07-06T23:00:00Z',status:'Scheduled',timezone:'America/Los_Angeles',assignees:[admin.email],reminderEmail:true,reminderSms:true}});
let queue=(await api('/control/followups')).records;assert.equal(queue.length,6);assert.equal(queue.filter(r=>r.data.phase==='morning')[0].data.dueAt,'2027-07-06T16:00:00.000Z');assert.equal(queue.filter(r=>r.data.phase==='hour-before')[0].data.dueAt,'2027-07-06T21:00:00.000Z');assert.ok(queue.every(r=>r.data.status==='On hold'));await api('/control/followups','POST',{});assert.equal((await api('/control/followups')).records.length,6);
let appt=(await api('/workspace/global/calendar/'+a.id)).record;await api('/workspace/global/calendar/'+a.id,'PUT',{version:appt.version,data:{...appt.data,start:'2027-07-07T22:00:00Z',end:'2027-07-07T23:00:00Z'}});queue=(await api('/control/followups')).records;assert.equal(queue.find(r=>r.data.phase==='morning').data.dueAt,'2027-07-07T16:00:00.000Z');
appt=(await api('/workspace/global/calendar/'+a.id)).record;await api('/workspace/global/calendar/'+a.id,'PUT',{version:appt.version,data:{...appt.data,status:'Cancelled'}});assert.ok((await api('/control/followups')).records.every(r=>r.data.status==='Cancelled'));
let contact=(await api('/workspace/global/contacts/'+id)).record;await api('/workspace/global/contacts/'+id,'PUT',{version:contact.version,data:{...contact.data,stage:'Paid'}});queue=(await api('/control/followups')).records.filter(r=>r.data.category==='campaign');assert.equal(queue.length,4);assert.ok(queue.every(r=>r.data.blocked==='Promotional permission needed'));contact=(await api('/workspace/global/contacts/'+id)).record;await api('/workspace/global/contacts/'+id,'PUT',{version:contact.version,data:{...contact.data,marketingEmailConsent:true,consentNote:'Test recorded permission 2026-09-16'}});queue=(await api('/control/followups')).records.filter(r=>r.data.category==='campaign'&&r.data.channel==='email');assert.ok(queue.every(r=>r.data.blocked==='Email provider not connected'));
const cfg=await api('/crm/global/settings');await api('/crm/global/settings','PUT',{version:cfg.version,data:{...cfg.data,tabs:[{id:'repairs',label:'Roof repairs',trade:'Roofing',specialty:'repair'}]}});assert.equal((await api('/crm/global/settings')).data.tabs[0].label,'Roof repairs');
contact=(await api('/workspace/global/contacts/'+id)).record;await api('/workspace/global/contacts/'+id+'/call-outcome','POST',{version:contact.version,outcome:'Voicemail'});assert.equal((await api('/workspace/global/contacts/'+id)).record.data.calls[0].outcome,'Voicemail');
const signal={title:'Public request',company:'Test Plumbing',excerpt:'Example evidence for a test only.',sourceUrl:'https://example.com/public-post',status:'Reviewed',trade:'Plumbing'};const sig=await api('/control/signals','POST',{data:signal});assert.equal((await api('/control/signals')).records.length,1);assert.equal((await req('/control/signals','POST',{data:{...signal,sourceUrl:'javascript:alert(1)'}})).status,400);await api('/control/signals','DELETE',{id:sig.record.id,version:sig.record.version});assert.equal((await api('/control/signals')).records.length,0);await api('/control/searches','POST',{phrase:'need a website',market:'Oxnard roofer'});assert.equal((await api('/control/searches')).records.length,1);
const operator={id:'operator',email:'operator@example.test'};const invite=await api('/team/invite','POST',{email:operator.email,role:'operator'});await api('/team/accept','POST',{token:invite.url.split('#')[1]},operator);assert.equal((await req('/control/settings','PUT',{version:0,data:s.record.data},operator)).status,403);
console.log('PASS control center: profiles/private photos, settings permissions, timezone/DST reminders, idempotent queues, rescheduling/cancellation, paid enrollment and promotional holds, custom contact tabs, call outcomes, reviewed public-source signals and saved searches. No external messages sent.');
