import assert from 'node:assert/strict';
import {worker,env,admin} from './preview-fixture.mjs';
const origin='https://test.local';
async function req(path,method='GET',data,user=admin,reqOrigin=origin){return worker.fetch(new Request(origin+path,{method,headers:{origin:reqOrigin,'content-type':'application/json',...(user?{'oai-authenticated-user-id':user.id,'oai-authenticated-user-email':user.email}:{})},body:data?JSON.stringify(data):undefined}),env)}
async function api(path,method='GET',data,user=admin){const r=await req(path,method,data,user);assert.equal(r.status,200,await r.clone().text());return r.json()}
const operator={id:'operator',email:'operator@example.test'},foreign={id:'foreign',email:'foreign@example.test'};
const invite=await api('/api/team/invite','POST',{email:operator.email,role:'operator'});const token=invite.url.split('#')[1];assert.equal((await req('/api/team/accept','POST',{token},foreign)).status,403);await api('/api/team/accept','POST',{token},operator);assert.equal((await req('/api/team/accept','POST',{token},operator)).status,410);const session=await api('/api/session','GET',null,operator);assert.equal(session.user.admin,false);assert.equal(session.user.staff,true);assert.equal((await req('/api/team','GET',null,operator)).status,403);assert.equal((await req('/api/workspace/global/payments','GET',null,operator)).status,403);assert.equal((await req('/api/team/invite','POST',{email:'x@example.test',role:'admin'},operator)).status,403);
const {id:leadId}=await api('/api/workspace/global/leads','POST',{data:{name:'Contact QA',company:'QA Roofing',stage:'New',trade:'Roofing',assignedTo:operator.email,tags:'warm,ventura',qualification:'Requested walkthrough',callOutcome:'Connected',notes:'A readable text note'}},operator);const lead=(await api('/api/workspace/global/leads/'+leadId,'GET',null,operator)).record;assert.equal(lead.data.trade,'Roofing');assert.equal(lead.data.notes,'A readable text note');
const appointment={title:'QA walkthrough',contactId:leadId,assignedTo:operator.email,start:'2026-11-03T18:00:00Z',end:'2026-11-03T19:00:00Z',timezone:'America/Los_Angeles',status:'Scheduled'};await api('/api/workspace/global/calendar','POST',{data:appointment},operator);assert.equal((await req('/api/workspace/global/calendar','POST',{data:{...appointment,start:'2026-11-03T18:30:00Z'}},operator)).status,409);await api('/api/workspace/global/calendar','POST',{data:{...appointment,assignedTo:admin.email}},operator);assert.equal((await req('/api/workspace/global/calendar','POST',{data:{...appointment,timezone:'NotAZone'}},operator)).status,400);
const tenant=(await api('/api/tenants')).tenants[0],base='/api/workspace/'+tenant.id;
assert.equal((await req(base+'/calendar','GET',null,operator)).status,404);const playbooks=await api('/api/tenants/'+tenant.id+'/playbooks');assert.equal(playbooks.playbooks.length,4);await api('/api/tenants/'+tenant.id+'/playbooks','POST',{id:'new-inquiry'});const steps=(await api(base+'/followups')).records;assert.equal(steps.length,3);assert.ok(steps.every(r=>!r.data.enabled));assert.equal((await req('/api/tenants/'+tenant.id+'/playbooks','POST',{id:'new-inquiry'},foreign)).status,404);
const blog={title:'Planning your roofing project',slug:'planning-your-roof',category:'Planning',excerpt:'Questions to prepare before a conversation.',body:'Write down the questions you want to discuss.\n\nBring photos that you can take safely from the ground. <script>no()</script>'};const {id:blogId}=await api(base+'/blog','POST',{data:blog});assert.equal((await req('/s/robles-roofing/blog/planning-your-roof','GET',null,null)).status,404);await api(base+'/blog/'+blogId+'/publish','POST',{version:1});let res=await req('/s/robles-roofing/blog/planning-your-roof','GET',null,null);assert.equal(res.status,200);assert.ok((await res.text()).includes('&lt;script&gt;'));assert.ok((await (await req('/s/robles-roofing/blog','GET',null,null)).text()).includes('Planning your roofing project'));
assert.equal((await req(base+'/blog','POST',{data:{...blog,slug:'other-url',coverPhotoId:'foreign-image'}})).status,400);
const {tenant:demo}=await api('/api/tenants','POST',{preset:'robles',slug:'demo-map-test'});await api('/api/tenants/'+demo.id+'/publish','POST',{version:demo.version,approved:true});const html=await (await req('/s/demo-map-test','GET',null,null)).text();assert.ok(html.includes('Demo portfolio'));assert.equal((html.match(/class="demo-label"/g)||[]).length,3);assert.equal((html.match(/id="lead-form"/g)||[]).length,1);assert.ok(html.includes('SUBMIT ESTIMATE REQUEST'));assert.ok(!html.includes('CALL FOR MY FREE ESTIMATE'));assert.ok(!html.includes('BENEATH THE SURFACE'));assert.ok(!html.includes('id="materials"'));assert.equal((await req('/s/demo-map-test/projects/demo-metal','GET',null,null)).status,200);assert.equal((await req('/api/public/demo-map-test/inquiries','POST',{name:'QA inquiry',phone:'8055550100',message:'test',consent:true,projectId:'demo-metal'},null)).status,404);
const info=(await api('/api/tenants/'+demo.id)).tenant;await api('/api/tenants/'+demo.id,'PUT',{settings:{...info.settings,showDemoProjects:false},version:info.version});const noDemos=await (await req('/s/demo-map-test?preview=1')).text();assert.ok(!noDemos.includes('Demo portfolio'));
await api('/api/team/revoke','POST',{kind:'member',id:operator.id});assert.equal((await req('/api/workspace/global/leads','GET',null,operator)).status,403);assert.equal((await req('/api/team/revoke','POST',{kind:'member',id:admin.id})).status,400);
console.log('PASS CRM: email-bound staff invitations, operator isolation, revocation, contact metadata, scoped appointments, overlap checks/timezone validation, disabled playbook drafts, blog draft privacy/escaping, image isolation, explicit demo projects, demo hide control, real submit form, removed materials section.');

await api('/api/public/demo-map-test/inquiries','POST',{name:'QA inbound',phone:'8055550111',message:'Please call about a roof.',consent:true},null);let inbound=(await api('/api/workspace/'+demo.id+'/contacts')).records;assert.equal(inbound.length,1);await api('/api/public/demo-map-test/inquiries','POST',{name:'QA inbound',phone:'8055550111',message:'Additional request details.',consent:true},null);inbound=(await api('/api/workspace/'+demo.id+'/contacts')).records;assert.equal(inbound.length,1);assert.equal(inbound[0].data.tags,'website inquiry');assert.equal((await api(base+'/blog')).records.filter(r=>r.data.title!=='Planning your roofing project').length,3);console.log('PASS inbound inquiries create one scoped contact per phone, and starter articles are saved as drafts.');
