import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import worker from '../dist/server/index.js';
const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const file of readdirSync('./drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('./drizzle/'+file,'utf8'));
const DB={prepare(query){let args=[];const statement={bind(...values){args=values;return statement},async first(){return sql.prepare(query).get(...args)||null},async all(){return {results:sql.prepare(query).all(...args)}},async run(){return {meta:{changes:Number(sql.prepare(query).run(...args).changes)}}}};return statement},async batch(statements){sql.exec('BEGIN');try{const result=[];for(const statement of statements)result.push(await statement.run());sql.exec('COMMIT');return result}catch(error){sql.exec('ROLLBACK');throw error}}};
const objects=new Map();let putHook=null;
const BUCKET={async put(key,value){const raw=value instanceof Uint8Array?value:new Uint8Array(await new Response(value).arrayBuffer());objects.set(key,raw);if(putHook)putHook(key)},async get(key){if(!objects.has(key))return null;const raw=objects.get(key);return {body:raw,text:async()=>new TextDecoder().decode(raw)}},async head(key){return objects.has(key)?{size:objects.get(key).length}:null},async delete(key){objects.delete(key)}};
const env={DB,BUCKET},admin={id:'admin',email:'yoelengel18@gmail.com'},alice={id:'alice',email:'alice@example.test'},bob={id:'bob',email:'bob@example.test'},viewer={id:'viewer',email:'viewer@example.test'};
async function request(path,method='GET',value,user=admin,origin='https://test.local'){return worker.fetch(new Request('https://test.local'+path,{method,headers:{origin,'Content-Type':value instanceof Uint8Array?'image/jpeg':'application/json',...(user?{'oai-authenticated-user-id':user.id,'oai-authenticated-user-email':user.email}:{})},body:value instanceof Uint8Array?value:value?JSON.stringify(value):undefined}),env)}
async function api(path,method='GET',value,user=admin){const r=await request('/api'+path,method,value,user);const d=await r.json();assert.ok(r.ok,`${method} ${path}: ${JSON.stringify(d)}`);return d}
assert.equal((await request('/api/setup','POST',{},alice)).status,403);await api('/setup','POST',{});assert.equal((await request('/api/tenants','POST',{},admin,'https://evil.test')).status,403);
let a=(await api('/tenants','POST',{preset:'robles',slug:'roof-a'})).tenant;
let b=(await api('/tenants','POST',{slug:'roof-b',settings:{name:'Test business B',trade:'Patios'}})).tenant;
assert.equal((await request('/api/tenants','GET',null,null)).status,401);
for(const [user,tenant,role]of [[alice,a,'owner'],[bob,b,'editor'],[viewer,a,'viewer']]){const invite=await api('/tenants/'+tenant.id+'/invites','POST',{email:user.email,role});const token=invite.url.split('#')[1];assert.equal((await request('/api/accept','POST',{token},{id:'wrong',email:'wrong@example.test'})).status,403);await api('/accept','POST',{token},user);assert.equal((await request('/api/accept','POST',{token},user)).status,410)}
assert.equal((await api('/tenants','GET',null,alice)).tenants.length,1);
assert.equal((await request('/api/tenants/'+b.id,'GET',null,alice)).status,404);
assert.equal((await request('/api/tenants/'+a.id,'PUT',{settings:a.settings,version:a.version},viewer)).status,403);
assert.equal((await request('/api/tenants/'+b.id+'/publish','POST',{approved:true,version:b.version},bob)).status,403);
assert.equal((await request('/api/audit','GET',null,alice)).status,403);
const project={title:'Verified repair <script>alert(1)</script>',city:'Oxnard',service:'Roof repair',material:'Asphalt shingle',concern:'Leak',property:'Residential',completedAt:'2025-01-01',lat:34.1975,lng:-119.1771,problem:'A documented roofing problem before the repair.',work:'Documented work completed on the roofing system.',outcome:'A verified result following completion of the work.',approved:true};
const pid=(await api('/tenants/'+a.id+'/projects','POST',project,alice)).id;
const jpeg=new Uint8Array(readFileSync('./public/assets/roofing.jpg'));
assert.equal((await request('/api/tenants/'+b.id+'/photos?projectId='+pid+'&stage=before','POST',jpeg,bob)).status,404);
const before=(await api('/tenants/'+a.id+'/photos?projectId='+pid+'&stage=before','POST',jpeg,alice)).id;
const after=(await api('/tenants/'+a.id+'/photos?projectId='+pid+'&stage=after','POST',jpeg,alice)).id;
assert.equal((await request('/media/'+before,'GET',null,bob)).status,404);
assert.equal((await request('/media/'+before,'GET',null,null)).status,401);
const alien=(await api('/tenants/'+b.id+'/photos?stage=brand','POST',jpeg,bob)).id;
assert.equal((await request('/api/tenants/'+a.id+'/projects/'+pid,'PUT',{version:1,data:{...project,coverId:alien}},alice)).status,400);
assert.equal((await request('/api/tenants/'+a.id+'/projects/'+pid,'PUT',{version:1,data:{...project,photoOrder:[alien]}},alice)).status,400);
await api('/tenants/'+a.id+'/projects/'+pid,'PUT',{version:1,data:{...project,beforeId:before,afterId:after}},alice);
await api('/tenants/'+a.id+'/projects/'+pid+'/publish','POST',{version:2},alice);
await api('/tenants/'+a.id+'/publish','POST',{version:a.version,approved:true},alice);
assert.equal((await request('/media/'+before,'GET',null,null)).status,200);
const html=await (await request('/s/roof-a/projects/'+pid,'GET',null,null)).text();assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('<script>alert(1)</script>'));
assert.equal((await request('/s/roof-b','GET',null,null)).status,404);
a=(await api('/tenants/'+a.id,'GET',null,alice)).tenant;
await api('/tenants/'+a.id,'PUT',{version:a.version,settings:{...a.settings,hero:'Unpublished headline'}},alice);
assert.ok(!(await (await request('/s/roof-a','GET',null,null)).text()).includes('Unpublished headline'));
assert.equal((await request('/api/tenants/'+a.id,'PUT',{version:a.version,settings:a.settings},alice)).status,409);
await api('/public/roof-a/inquiries','POST',{name:'Local test only',phone:'8055550199',message:'Test',consent:true,projectId:pid},null);
assert.equal((await api('/tenants/'+a.id,'GET',null,alice)).inquiries.length,1);
assert.equal((await api('/tenants/'+b.id,'GET',null,bob)).inquiries.length,0);
const backup=(await api('/tenants/'+a.id+'/backups','POST',{},alice)).id;
assert.equal((await request('/api/tenants/'+b.id+'/backups/'+backup+'/download','GET',null,bob)).status,403);
assert.ok([...objects.keys()].some(key=>key.includes('/'+backup+'/media/')));
a=(await api('/tenants/'+a.id,'GET',null,alice)).tenant;
putHook=key=>{if(key.endsWith('/snapshot.json')){sql.prepare('UPDATE tenants SET version=version+1 WHERE id=?').run(a.id);putHook=null}};
assert.equal((await request('/api/tenants/'+a.id+'/backups/'+backup+'/restore','POST',{version:a.version,confirm:true},alice)).status,409);
assert.ok(sql.prepare('SELECT published FROM projects WHERE id=?').get(pid).published,'Stale restore must not unpublish projects');
a=(await api('/tenants/'+a.id,'GET',null,alice)).tenant;
await api('/tenants/'+a.id+'/backups/'+backup+'/restore','POST',{version:a.version,confirm:true},alice);
const restored=(await api('/tenants/'+a.id,'GET',null,alice));assert.equal(restored.tenant.status,'draft');assert.equal(restored.tenant.settings._restore,undefined);assert.equal(restored.projects[0].published,null);assert.equal(restored.inquiries.length,1);
assert.equal((await request('/s/roof-a','GET',null,null)).status,404);
const dup=await api('/tenants/'+a.id+'/duplicate','POST',{slug:'separate-copy',name:'Separate business'});const copy=await api('/tenants/'+dup.id);assert.equal(copy.tenant.settings.phone,'');assert.equal(copy.projects.length,0);assert.equal(copy.photos.length,0);
const checks=await api('/health','POST',{});assert.ok(checks.check.database.ok&&checks.check.storage.ok);
const member=sql.prepare('SELECT id FROM members WHERE user_id=?').get(alice.id);await api('/tenants/'+a.id+'/members/'+member.id+'/revoke','POST',{});assert.equal((await request('/api/tenants/'+a.id,'GET',null,alice)).status,404);
console.log('PASS: initialization, origin checks, account isolation, invitations, roles, cross-tenant uploads, private photos, draft snapshots, publishing, escaped stories, inquiry attribution, copied-photo backups, concurrent restore guard, restoration, duplication, health checks, revocation.');
