import assert from 'node:assert/strict';
import {worker,env,admin} from './preview-fixture.mjs';
const origin='https://test.local';
async function req(path,method='GET',data,user=admin){return worker.fetch(new Request(origin+path,{method,headers:{origin,'content-type':'application/json',...(user?{'oai-authenticated-user-id':user.id,'oai-authenticated-user-email':user.email}:{})},body:data?JSON.stringify(data):undefined}),env)}
async function api(path,method='GET',data,user=admin){const r=await req(path,method,data,user);assert.equal(r.status,200,await r.clone().text());return r.json()}
const operator={id:'sales-op',email:'sales@example.test'};const inv=await api('/api/team/invite','POST',{email:operator.email,role:'operator'});await api('/api/team/accept','POST',{token:inv.url.split('#')[1]},operator);
const statement={memberEmail:operator.email,month:'2026-09',role:'Closer',collected:2000,refunds:200,rate:10,bonus:50,base:100,adjustment:-10,quota:3000,status:'Draft',reference:'QA reconciliation'};
const {id}=await api('/api/workspace/global/commissions','POST',{data:statement});let r=(await api('/api/workspace/global/commissions/'+id)).record;assert.equal(r.data.commission,180);assert.equal(r.data.total,320);
assert.equal((await req('/api/workspace/global/commissions','POST',{data:statement},operator)).status,403);
assert.equal((await req('/api/workspace/global/commissions','POST',{data:statement})).status,409);
const other=await api('/api/workspace/global/commissions','POST',{data:{...statement,memberEmail:'other@example.test'}});assert.equal((await api('/api/workspace/global/commissions','GET',null,operator)).records.length,1);assert.equal((await req('/api/workspace/global/commissions/'+other.id,'GET',null,operator)).status,404);
assert.equal((await req('/api/workspace/global/commissions/'+id,'PUT',{version:r.version,data:{...statement,status:'Paid'}})).status,400);
assert.equal((await req('/api/workspace/global/commissions/'+id,'PUT',{version:r.version,data:{...statement,rate:101}})).status,400);
await api('/api/workspace/global/commissions/'+id,'PUT',{version:r.version,data:{...statement,status:'Approved'}});assert.equal((await req('/api/workspace/global/commissions/'+id,'PUT',{version:r.version,data:statement})).status,409);
await api('/api/workspace/global/leads/import','POST',{rows:[{company:'Mapped Co',name:'Mapped Person',phone:'8055550201',custom:{'Roof size':'2500 sq ft','Referral source':'Trade show'}}]},operator);let contact=(await api('/api/workspace/global/leads')).records.find(x=>x.data.company==='Mapped Co');assert.equal(contact.data.custom['Roof size'],'2500 sq ft');await api('/api/workspace/global/leads/'+contact.id,'PUT',{version:contact.version,data:{...contact.data,notes:'Updated call notes'}},operator);contact=(await api('/api/workspace/global/leads/'+contact.id)).record;assert.equal(contact.data.custom['Referral source'],'Trade show');
const {tenant}=await api('/api/tenants','POST',{preset:'robles',slug:'story-layout-test'});await api('/api/tenants/'+tenant.id+'/publish','POST',{version:tenant.version,approved:true});const story=await (await req('/s/story-layout-test/projects/demo-metal','GET',null,null)).text();for(const text of ['project-story','story-intro','story-showcase','story-brief','DEMONSTRATION STORY','project-story.css'])assert.ok(story.includes(text),text);assert.ok(story.includes('class="comparison"'));assert.ok(story.includes('different jobs'));assert.equal((story.match(/id="lead-form"/g)||[]).length,1);assert.equal((await req('/api/workspace/'+tenant.id+'/commissions')).status,403);
console.log('PASS sales operations: commission calculation, own-record access, admin write gates, reconciliation/payout validation, duplicates and stale writes; custom imported fields survive edits; scoped project-story demo rendering.');
