import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {worker,env,admin} from './preview-fixture.mjs';
const origin='https://test.local';
async function request(path,method='GET',body,user=admin){return worker.fetch(new Request(origin+path,{method,headers:{origin,'content-type':'application/json',...(user?{'oai-authenticated-user-id':user.id,'oai-authenticated-user-email':user.email}:{})},body:body?JSON.stringify(body):undefined}),env)}
async function api(path,method='GET',body){const r=await request('/api'+path,method,body);assert.equal(r.status,200,await r.clone().text());return r.json()}
const {tenant:original}=await api('/tenants','POST',{designKit:'plumbing',slug:'before-saving',settings:{name:'Existing plumbing company',services:[{name:'Leak detection'}],design:{font:'modern',heroFrame:'arch'},template:'editorial'}});
const saved=await api('/design-library','POST',{name:'Flow Architect',snapshot:original.settings});let library=(await api('/design-library')).designs;assert.equal(library.length,1);assert.equal(library[0].uses.length,1,'existing matching site backfilled');const same=await api('/design-library','POST',{name:'Other name',snapshot:original.settings});assert.equal(same.id,saved.id);assert.equal(same.existing,true);
const {tenant:t}=await api('/tenants','POST',{designKit:'plumbing',slug:'saved-second',settings:{...original.settings,name:'Second plumbing company',savedDesignId:saved.id}});assert.equal(t.settings.savedDesignId,saved.id);library=(await api('/design-library')).designs;assert.equal(library[0].uses.length,2);
const {tenant:updated}=await api('/tenants/'+t.id,'PUT',{version:t.version,settings:{...t.settings,phone:'8055550199'}});assert.equal((await api('/design-library')).designs[0].uses.length,2,'no duplicate uses for ordinary edits');const {tenant:changed}=await api('/tenants/'+t.id,'PUT',{version:updated.version,settings:{...updated.settings,design:{...updated.settings.design,font:'editorial'}}});assert.equal(changed.settings.savedDesignId,'');assert.equal((await api('/design-library')).designs[0].uses.length,2,'historical use retained');
const {tenant:third}=await api('/tenants','POST',{designKit:'plumbing',slug:'automatic-match',settings:{...original.settings,name:'Third company'}});assert.equal(third.settings.savedDesignId,saved.id,'equivalent unsaved selection matches existing favorite');await api('/tenants/'+third.id+'/duplicate','POST',{name:'Fourth company',slug:'duplicate-design'});assert.equal((await api('/design-library')).designs[0].uses.length,4);
assert.equal((await request('/api/design-library','GET',null,{id:'outsider',email:'outside@example.test'})).status,403);assert.equal((await request('/api/design-library','GET',null,null)).status,401);
for(const id of ['roofing','patios','plumbing','hvac','electrical','landscaping','general-contractors']){const h=await(await request('/design-preview/'+id+'/immersive?heroFrame=arch&entrance=mask&palette=ocean')).text();assert.ok(h.includes('hero-frame-arch entrance-mask palette-ocean'));assert.ok(h.includes('id="job-map"'));assert.ok(h.includes('id="project-data"'));assert.ok(h.includes('/assets/films/'+id+'-transformation.mp4'));assert.ok((h.match(/href="#contact"/g)||[]).length>=8);assert.ok(h.includes('not jobs completed by this business'));assert.equal((h.match(/id="lead-form"/g)||[]).length,1)}
const h=await(await request('/design-preview/roofing/studio?commercial=false&ctaBands=false&projectMap=false&planning=false&chapterRail=false')).text();assert.ok(!h.includes('<video'));assert.ok(!h.includes('kit-cta-band'));assert.ok(!h.includes('id="job-map"'));assert.ok(!h.includes('class="kit-chapter-rail"'));
const films=JSON.parse(readFileSync('public/trade-films.json'));for(const film of Object.values(films)){assert.ok(existsSync('public'+film.url));assert.ok(readFileSync('public'+film.url).subarray(0,30).includes(Buffer.from('ftyp')))}
console.log('PASS saved-template persistence, matching existing sites, unique contractor counts, historical usage, reuse, duplication, access isolation, seven trade films/maps/CTAs, variants and optional ingredients.');
