import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {cleanFields,fieldAnswers,fieldMarkup} from '../src/form-fields.js';
import {cleanDesign} from '../src/design-variant.js';
import {cleanReviews,reviewsApi} from '../src/reviews.js';
import {worker,env,admin} from './preview-fixture.mjs';
const fields=cleanFields([{key:'field_a',label:'Work',type:'radio',options:['Repair','Replace'],required:true},{key:'field_b',label:'Materials',type:'checkboxes',options:['Metal','Shingle'],required:true},{key:'field_c',label:'Area',type:'number',min:10,max:100},{key:'field_d',label:'Agree',type:'checkbox',required:true}]);
assert.equal(fields[0].key,'field_a');assert.throws(()=>fieldAnswers(fields,{field_a:'Other'}));assert.throws(()=>fieldAnswers(fields,{field_a:'Repair',field_b:[],field_d:true}));assert.throws(()=>fieldAnswers(fields,{field_a:'Repair',field_b:['Metal'],field_c:101,field_d:true}));assert.deepEqual(fieldAnswers(fields,{field_a:'Repair',field_b:['Metal'],field_c:20,field_d:true}).Materials,['Metal']);assert.ok(fieldMarkup(fields[1]).includes('data-group-required'));assert.throws(()=>cleanFields([{label:'Same'},{label:'same'}]));assert.equal(cleanFields([{label:'Legacy'}])[0].key,'field0');assert.equal(cleanDesign({font:'<script>'}).font,'display');assert.throws(()=>cleanReviews({googleUrl:'https://evil.test/google.com'}));
const art=JSON.parse(readFileSync('public/service-art.json')),trades=JSON.parse(readFileSync('public/trade-library.json'));for(const [trade,names]of Object.entries(trades))for(const name of names)assert.ok(existsSync('public'+art[trade][name.toLowerCase()]),trade+name);const cuts=JSON.parse(readFileSync('public/cutaways.json'));assert.equal(Object.keys(cuts).length,7);for(const d of Object.values(cuts)){assert.ok(existsSync('public'+d.image));assert.equal(d.hotspots.length,4);for(const h of d.hotspots)assert.ok(h.x>0&&h.x<100&&h.y>0&&h.y<100)}
const headers={'oai-authenticated-user-id':admin.id,'oai-authenticated-user-email':admin.email};let r=await worker.fetch(new Request('https://test.local/design-preview/hvac/editorial?font=modern&cards=soft&cutaway=false',{headers}),env);let html=await r.text();assert.ok(html.includes('font-modern cards-soft'));assert.ok(!html.includes('cutaway-stage'));assert.equal((html.match(/class="service-art"/g)||[]).length,8);
const t=await env.DB.prepare('SELECT * FROM tenants WHERE slug=?').bind('robles-roofing').first();const s=JSON.parse(t.published);s.reviews=cleanReviews({googleUrl:'https://www.google.com/maps/place/test',googlePlaceId:'test',privacyUrl:'https://test.local/privacy',termsUrl:'https://test.local/terms',minimum:4,confirmed:true});await env.DB.prepare('UPDATE tenants SET published=? WHERE id=?').bind(JSON.stringify(s),t.id).run();let result=await reviewsApi(new Request('https://test.local/api/public/robles-roofing/reviews'),env,new URL('https://test.local/api/public/robles-roofing/reviews'));assert.ok(result.providers[0].status.includes('API connection'));const original=globalThis.fetch;globalThis.fetch=async()=>Response.json({rating:3.8,userRatingCount:50,displayName:{text:'Real business'},reviews:[{rating:5,text:{text:'Good'},authorAttribution:{displayName:'Test author'}},{rating:2,text:{text:'Bad'}}]});try{result=await reviewsApi(new Request('https://test.local/api/public/robles-roofing/reviews'),{...env,GOOGLE_PLACES_API_KEY:'test-only'},new URL('https://test.local/api/public/robles-roofing/reviews'));assert.equal(result.providers[0].rating,3.8);assert.equal(result.providers[0].count,50);assert.equal(result.providers[0].reviews.length,1);assert.equal(result.providers[0].reviews[0].author,'Test author')}finally{globalThis.fetch=original}
console.log('PASS typed forms, invalid/tampered submissions, 56 service mappings, 7 cutaways, variant rendering, source links, missing API setup, unchanged aggregate and selected review excerpts.');
