import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {worker,env,admin} from './preview-fixture.mjs';
const origin='https://test.local';
async function req(path,method='GET',value,user=admin,requestOrigin=origin){return worker.fetch(new Request(origin+path,{method,headers:{origin:requestOrigin,'content-type':'application/json',...(user?{'oai-authenticated-user-id':user.id,'oai-authenticated-user-email':user.email}:{})},body:value?JSON.stringify(value):undefined}),env)}
async function json(path,method='GET',value,user=admin){const r=await req(path,method,value,user);assert.equal(r.status,200,await r.clone().text());return r.json()}
const tenant=(await json('/api/tenants')).tenants[0],scope='/api/workspace/'+tenant.id;
for(const [id,role] of [['owner','owner'],['editor','editor'],['viewer','viewer']])await env.DB.prepare('INSERT INTO members(id,tenant_id,user_id,email,role,active,created_at) VALUES(?,?,?,?,?,1,?)').bind(id,tenant.id,id,id+'@example.test',role,new Date().toISOString()).run();
const owner={id:'owner',email:'owner@example.test'},editor={id:'editor',email:'editor@example.test'},viewer={id:'viewer',email:'viewer@example.test'},outsider={id:'stranger',email:'stranger@example.test'};
assert.equal((await req(scope+'/pages','GET',null,outsider)).status,404);assert.equal((await req('/api/workspace/global/leads','GET',null,owner)).status,403);
assert.equal((await req(scope+'/support','POST',{},owner)).status,403);await json(scope+'/support','POST',{});assert.ok((await json('/api/audit')).events.some(x=>x.action==='support.entered'));
assert.equal((await req(scope+'/pages','POST',{title:'Blocked'},viewer)).status,403);assert.equal((await req(scope+'/pages','POST',{},admin,'https://evil.test')).status,403);
const page={title:'Roof care',slug:'roof-care',body:'Useful roof care information for our visitors. <script>bad()</script>',showInNav:true};const {id}=await json(scope+'/pages','POST',{data:page},editor);
assert.equal((await req('/s/robles-roofing/pages/roof-care','GET',null,null)).status,404);assert.equal((await req(scope+'/pages/'+id+'/publish','POST',{version:1},editor)).status,403);
await json(scope+'/pages/'+id+'/publish','POST',{version:1},owner);let res=await req('/s/robles-roofing/pages/roof-care','GET',null,null);assert.equal(res.status,200);assert.ok((await res.text()).includes('&lt;script&gt;'));
assert.equal((await req(scope+'/pages','POST',{data:page},owner)).status,409);assert.equal((await req(scope+'/pages/'+id,'PUT',{data:page,version:1},owner)).status,409);
const {id:form}=await json(scope+'/forms','POST',{data:{name:'Ask a question',fields:[{label:'What is happening?',required:true}],active:true}},owner);await json(scope+'/forms/'+form+'/publish','POST',{version:1},owner);
const formPath='/s/robles-roofing/forms/'+form,submission={name:'Test visitor',email:'test@example.test',field0:'A roof question',consent:true};assert.equal((await req(formPath,'POST',{...submission,consent:false},null)).status,400);await json(formPath,'POST',submission,null);assert.equal((await json(scope+'/submissions','GET',null,owner)).records.length,1);assert.equal((await req(scope+'/submissions','POST',{},owner)).status,403);
const {id:plan}=await json(scope+'/plan','POST',{data:{plan:'Starter',features:{forms:false,ai:false}}});assert.equal((await req(formPath,'GET',null,null)).status,404);assert.equal((await req(scope+'/forms','POST',{data:{name:'Disabled'}},owner)).status,403);assert.equal((await req(scope+'/plan/'+plan,'PUT',{data:{plan:'Pro'},version:1},owner)).status,403);
assert.equal((await req(scope+'/ai','POST',{field:'description'},owner)).status,403);await json(scope+'/plan/'+plan,'PUT',{data:{plan:'Pro',features:{ai:true}},version:1});assert.equal((await req(scope+'/ai','POST',{field:'license'},owner)).status,400);assert.equal((await req(scope+'/ai','POST',{field:'description',current:''},owner)).status,409);
const imported=await json('/api/workspace/global/leads/import','POST',{rows:[{company:'Example',stage:'New'},{company:'Example',stage:'New'}]});assert.equal(imported.imported,1);assert.equal(imported.skipped,1);assert.equal((await req('/api/workspace/global/leads/import','POST',{rows:[{company:'Bad',stage:'Fake'}]})).status,400);
const payment={type:'Proposal',title:'Website setup',customer:'QA Customer',amount:750,description:'QA proposal scope. Not a real transaction.',terms:'For testing only.'};const {id:proposal}=await json('/api/workspace/global/payments','POST',{data:payment});await json('/api/workspace/global/payments/'+proposal+'/publish','POST',{version:1});const pr=(await json('/api/workspace/global/payments/'+proposal)).record;assert.ok(pr.published.token);const path='/proposal/'+pr.published.token;assert.equal((await req(path,'GET',null,null)).status,200);await json(path,'POST',{name:'QA approver',approved:true,version:pr.version},null);assert.equal((await req(path,'POST',{name:'QA approver',approved:true,version:pr.version},null)).status,409);assert.equal((await req('/api/workspace/global/payments/'+proposal,'PUT',{data:payment,version:3})).status,400);
assert.equal((await req('/api/workspace/global/payments','POST',{data:{...payment,paymentUrl:'https://evil.test/pay'}})).status,400);
const preview=await req('/preview/robles-roofing');assert.equal(preview.status,200);assert.ok((await preview.text()).includes('Mobile'));assert.equal((await req('/preview/robles-roofing','GET',null,null)).status,401);
const backup=await json('/api/tenants/'+tenant.id+'/backups','POST',{});const downloaded=await json('/api/tenants/'+tenant.id+'/backups/'+backup.id+'/download');assert.ok(downloaded.workspaceRecords.some(r=>r.id===id));
const site=await req('/s/robles-roofing');const html=await site.text();assert.ok(html.includes('roof-services-grid'));assert.equal((html.split('roof-services-grid')[1].split('</section>')[0].match(/<article>/g)||[]).length,8);
console.log('PASS workspace: role isolation, audited admin access, draft/public separation, page escaping/uniqueness, form consent/submissions, server plan enforcement, AI setup gate, lead import dedup, proposal approvals/locking, payment URL validation, device preview auth, workspace backups, 8-card roof grid.');

const photoResponse=await worker.fetch(new Request(origin+'/api/tenants/'+tenant.id+'/photos?stage=brand&caption=Owner%20test',{method:'POST',headers:{origin,'content-type':'image/jpeg','oai-authenticated-user-id':owner.id,'oai-authenticated-user-email':owner.email},body:readFileSync('./public/assets/roofing.jpg')}),env);assert.equal(photoResponse.status,200);const portrait=await photoResponse.json();let latest=(await json('/api/tenants/'+tenant.id)).tenant;await json('/api/tenants/'+tenant.id,'PUT',{settings:{...latest.settings,ownerPhotoId:portrait.id,showOwnerPhoto:true},version:latest.version},owner);assert.ok((await (await req('/s/robles-roofing?preview=1','GET',null,owner)).text()).includes('src="/media/'+portrait.id+'"'));assert.equal((await req('/media/'+portrait.id,'GET',null,null)).status,401);
let pageRecord=(await json(scope+'/pages/'+id)).record;await json(scope+'/pages/'+id,'PUT',{data:{...pageRecord.data,body:'Changed page after backup.'},version:pageRecord.version});latest=(await json('/api/tenants/'+tenant.id)).tenant;await json('/api/tenants/'+tenant.id+'/backups/'+backup.id+'/restore','POST',{version:latest.version,confirm:true});pageRecord=(await json(scope+'/pages/'+id)).record;assert.equal(pageRecord.data.body,page.body);assert.equal(pageRecord.published,null);assert.equal((await json(scope+'/submissions')).records.length,1);console.log('PASS owner upload selection/private media and workspace page restoration with submissions retained.');
