import assert from 'node:assert/strict';
import {worker,env,admin} from './preview-fixture.mjs';
const origin='https://test.local';
async function api(path,method='GET',data){const res=await worker.fetch(new Request(origin+'/api'+path,{method,headers:{origin,'content-type':'application/json','oai-authenticated-user-id':admin.id,'oai-authenticated-user-email':admin.email},body:data?JSON.stringify(data):undefined}),env);assert.equal(res.status,200,await res.clone().text());return res.json()}
const path='/workspace/global/calendar';const appointment={title:'Zoom demo',meetingType:'Zoom',start:'2027-01-02T18:00:00Z',end:'2027-01-02T19:00:00Z',status:'Scheduled',timezone:'America/Los_Angeles',assignees:[admin.email]};
assert.equal((await api('/crm/global/zoom')).configured,false);const first=await api(path,'POST',{data:appointment});assert.equal(first.zoom.status,'not_connected');
Object.assign(env,{ZOOM_ACCOUNT_ID:'test',ZOOM_CLIENT_ID:'test',ZOOM_CLIENT_SECRET:'test',ZOOM_HOST_USER_ID:'host@example.test'});const originalFetch=globalThis.fetch;let created=0,updated=0;globalThis.fetch=async(url,options)=>{if(url==='https://zoom.us/oauth/token')return Response.json({access_token:'test-token'});assert.ok(url.startsWith('https://api.zoom.us/v2/'));if(options.method==='POST'){created++;const payload=JSON.parse(options.body);assert.equal(payload.type,2);assert.equal(payload.settings.waiting_room,true);return Response.json({id:123,join_url:'https://zoom.us/j/123',start_url:'https://zoom.us/host-private'})}updated++;return new Response(null,{status:204})};
try{let r=(await api(path+'/'+first.id)).record;let saved=await api(path+'/'+first.id,'PUT',{version:r.version,data:r.data});assert.equal(saved.zoom.status,'ready');assert.equal(created,1);r=(await api(path+'/'+first.id)).record;assert.equal(r.data.location,'https://zoom.us/j/123');assert.ok(!JSON.stringify(r).includes('host-private'));await api(path+'/'+first.id,'PUT',{version:r.version,data:r.data});assert.equal(created,1);assert.equal(updated,0);r=(await api(path+'/'+first.id)).record;await api(path+'/'+first.id,'PUT',{version:r.version,data:{...r.data,title:'Updated walkthrough'}});assert.equal(updated,1);assert.equal(created,1);
 globalThis.fetch=async url=>{if(url==='https://zoom.us/oauth/token')return Response.json({access_token:'test'});throw Error('Network timeout')};const second=await api(path,'POST',{data:{...appointment,start:'2027-01-03T18:00:00Z',end:'2027-01-03T19:00:00Z'}});assert.equal(second.zoom.status,'uncertain');r=(await api(path+'/'+second.id)).record;const retry=await api(path+'/'+second.id,'PUT',{version:r.version,data:r.data});assert.equal(retry.zoom.status,'uncertain');
 console.log('PASS Zoom: explicit disconnected state, automatic creation, saved participant link only, repeat-save deduplication, reschedule update, uncertain-request duplicate prevention. No real Zoom API calls made.');
}finally{globalThis.fetch=originalFetch}
