import {sqliteTable,text,integer,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const admins=sqliteTable('admins',{role:text('role').notNull().default('admin'),userId:text('user_id').primaryKey(),email:text('email').notNull(),createdAt:text('created_at').notNull()});
export const tenants=sqliteTable('tenants',{id:text('id').primaryKey(),slug:text('slug').notNull().unique(),name:text('name').notNull(),settings:text('settings').notNull(),published:text('published'),version:integer('version').notNull().default(1),status:text('status').notNull().default('draft'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()});
export const members=sqliteTable('members',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull().references(()=>tenants.id),userId:text('user_id').notNull(),email:text('email').notNull(),role:text('role').notNull(),active:integer('active').notNull().default(1),createdAt:text('created_at').notNull()},t=>[uniqueIndex('members_identity').on(t.tenantId,t.userId)]);
export const invites=sqliteTable('invites',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull().references(()=>tenants.id),email:text('email').notNull(),role:text('role').notNull(),tokenHash:text('token_hash').notNull().unique(),expiresAt:text('expires_at').notNull(),usedAt:text('used_at'),revoked:integer('revoked').notNull().default(0),createdAt:text('created_at').notNull()});
export const projects=sqliteTable('projects',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull().references(()=>tenants.id),data:text('data').notNull(),published:text('published'),version:integer('version').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('projects_tenant').on(t.tenantId)]);
export const photos=sqliteTable('photos',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull().references(()=>tenants.id),projectId:text('project_id').references(()=>projects.id),objectKey:text('object_key').notNull(),caption:text('caption').notNull().default(''),stage:text('stage').notNull(),bytes:integer('bytes').notNull(),createdAt:text('created_at').notNull()},t=>[index('photos_tenant').on(t.tenantId)]);
export const domains=sqliteTable('domains',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull().references(()=>tenants.id),hostname:text('hostname').notNull().unique(),token:text('token').notNull(),ownership:text('ownership').notNull().default('pending'),checkedAt:text('checked_at'),createdAt:text('created_at').notNull()});
export const backups=sqliteTable('backups',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull().references(()=>tenants.id),objectKey:text('object_key').notNull(),reason:text('reason').notNull(),bytes:integer('bytes').notNull(),checksum:text('checksum').notNull(),createdAt:text('created_at').notNull()});
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),tenantId:text('tenant_id'),actor:text('actor').notNull(),action:text('action').notNull(),detail:text('detail').notNull(),createdAt:text('created_at').notNull()},t=>[index('audit_tenant').on(t.tenantId,t.createdAt)]);
export const health=sqliteTable('health',{id:text('id').primaryKey(),data:text('data').notNull(),createdAt:text('created_at').notNull()});
export const inquiries=sqliteTable('inquiries',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull().references(()=>tenants.id),projectId:text('project_id'),name:text('name').notNull(),phone:text('phone').notNull(),message:text('message').notNull(),createdAt:text('created_at').notNull()},t=>[index('inquiries_tenant').on(t.tenantId)]);
export const sales=sqliteTable('sales',{tenantId:text('tenant_id').primaryKey().references(()=>tenants.id),data:text('data').notNull(),version:integer('version').notNull().default(1),updatedAt:text('updated_at').notNull()});

export const workspaceRecords=sqliteTable('workspace_records',{id:text('id').primaryKey(),scope:text('scope').notNull(),kind:text('kind').notNull(),data:text('data').notNull(),published:text('published'),version:integer('version').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('workspace_scope_kind').on(t.scope,t.kind)]);

export const chatThreads=sqliteTable('chat_threads',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull().references(()=>tenants.id),tokenHash:text('token_hash').notNull(),reference:text('reference').notNull().unique(),name:text('name').notNull(),phone:text('phone').notNull().default(''),email:text('email').notNull().default(''),status:text('status').notNull().default('open'),human:integer('human').notNull().default(0),messageCount:integer('message_count').notNull().default(0),ipHash:text('ip_hash').notNull(),notification:text('notification').notNull().default('not_requested'),lockUntil:text('lock_until').notNull().default(''),expiresAt:text('expires_at').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('chat_tenant_updated').on(t.tenantId,t.updatedAt),index('chat_tenant_ip_created').on(t.tenantId,t.ipHash,t.createdAt)]);
export const chatMessages=sqliteTable('chat_messages',{id:text('id').primaryKey(),threadId:text('thread_id').notNull().references(()=>chatThreads.id),sender:text('sender').notNull(),body:text('body').notNull(),providerId:text('provider_id').unique(),createdAt:text('created_at').notNull()},t=>[index('chat_thread_created').on(t.threadId,t.createdAt)]);
