import {validateSavedDesign,recordDesignUse} from './saved-designs.js';
import {kitDefaults,kits} from './design-kits.js';
import {createStarterArticles} from './blog-starters.js';
import {demoProjects} from './crm.js';
import {readiness,salesData} from './builder.js';
import {sitePage} from './views.js';
import {uid,now,e,text,Fault,must,db,one,all,run,hash,bytes,body,person,identity,access,log,DEFAULT,ROBLES,settings,tenantView,projectData,jpeg} from './core.js';
import {snapshot,backupContent,restore,checkHealth} from './operations.js';
export async function api(req,env,url){const path=url.pathname,method=req.method;
if(method!=='GET')must(req.headers.get('origin')===url.origin,'Request must originate from this website.',403);
if(path==='/api/session'){const p=person(req);if(p){const t=now();await run(env,"INSERT INTO workspace_records(id,scope,kind,data,created_at,updated_at) VALUES(?,'global','user_seen',?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at",'seen-'+p.id,JSON.stringify({lastSeen:t}),t,t)}return {user:p?await identity(req,env):null,initialized:!!await one(env,'SELECT user_id FROM admins LIMIT 1')}}
if(path==='/api/setup'&&method==='POST'){const p=person(req);must(p,'Sign in first.',401);must(p.email==='yoelengel18@gmail.com','Only the Buildovate workspace owner can initialize this platform.',403);must(!await one(env,'SELECT user_id FROM admins WHERE user_id<>?',p.id),'Workspace already initialized.',409);await run(env,'INSERT OR IGNORE INTO admins (user_id,email,created_at) VALUES (?,?,?)',p.id,p.email,now());return {ok:true}}
if(path==='/api/accept'&&method==='POST'){const p=await identity(req,env),v=await body(req),invite=await one(env,'SELECT * FROM invites WHERE token_hash=?',await hash(text(v.token,100)));must(invite&&!invite.used_at&&!invite.revoked&&invite.expires_at>now(),'Invitation is expired, revoked, or already used.',410);must(p.email===invite.email,'Sign in using the email address on this invitation.',403);const t=now();const results=await db(env).batch([db(env).prepare('INSERT INTO members (id,tenant_id,user_id,email,role,active,created_at) SELECT ?,tenant_id,?,?,role,1,? FROM invites WHERE id=? AND used_at IS NULL AND revoked=0 AND expires_at>? ON CONFLICT(tenant_id,user_id) DO UPDATE SET role=excluded.role,active=1').bind(uid(),p.id,p.email,t,invite.id,t),db(env).prepare('UPDATE invites SET used_at=? WHERE id=? AND used_at IS NULL AND revoked=0').bind(t,invite.id)]);must(results[0].meta.changes,'Invitation no longer available.',410);await log(env,p,invite.tenant_id,'member.joined',invite.role);return {ok:true,tenantId:invite.tenant_id}}
const user=await identity(req,env);
if(path==='/api/tenants'&&method==='GET'){const rows=user.admin?await all(env,'SELECT * FROM tenants ORDER BY created_at DESC'):await all(env,'SELECT tenants.*,members.role FROM tenants JOIN members ON members.tenant_id=tenants.id WHERE members.user_id=? AND members.active=1 ORDER BY tenants.created_at DESC',user.id);return {tenants:rows.map(tenantView)}}
if(path==='/api/tenants'&&method==='POST'){must(user.admin,'Buildovate administrator access required.',403);const v=await body(req),s=settings(v.preset==='robles'?ROBLES:{...DEFAULT,...(v.designKit?kitDefaults(v.designKit,v.settings||{}):v.settings)}),slug=text(v.slug,60).toLowerCase();await validateSavedDesign(env,s);if(v.designKit)must(kits[v.designKit]&&s.services.length,'Choose a design and at least one offered specialty.');must(/^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/.test(slug),'Use a lowercase URL name with letters, numbers, and single hyphens.');must(!await one(env,'SELECT id FROM tenants WHERE slug=?',slug),'That URL name is already in use.',409);const id=uid(),t=now();await run(env,'INSERT INTO tenants (id,slug,name,settings,created_at,updated_at) VALUES (?,?,?,?,?,?)',id,slug,s.name,JSON.stringify(s),t,t);await recordDesignUse(env,s,id);await createStarterArticles(env,id);await log(env,user,id,'website.provisioned',slug);return {tenant:tenantView(await one(env,'SELECT * FROM tenants WHERE id=?',id))}}
if(path==='/api/pipeline'&&method==='GET'){must(user.admin,'Administrator access required.',403);return {records:(await all(env,'SELECT tenants.id,tenants.name,tenants.slug,tenants.status,sales.data,sales.version,sales.updated_at FROM tenants LEFT JOIN sales ON sales.tenant_id=tenants.id ORDER BY tenants.created_at DESC')).map(r=>({...r,data:r.data?JSON.parse(r.data):{stage:'Prospect',amount:750},version:r.version||0}))}}
if(path==='/api/health'){must(user.admin,'Administrator access required.',403);if(method==='POST')return {check:await checkHealth(env)};return {checks:(await all(env,'SELECT * FROM health ORDER BY created_at DESC LIMIT 20')).map(h=>({...JSON.parse(h.data),id:h.id})),errors:await all(env,"SELECT * FROM audit WHERE action='system.error' ORDER BY created_at DESC LIMIT 30")}}
if(path==='/api/audit'&&method==='GET'){must(user.admin,'Administrator access required.',403);return {events:await all(env,'SELECT audit.*,tenants.name AS tenant_name FROM audit LEFT JOIN tenants ON tenants.id=audit.tenant_id ORDER BY audit.created_at DESC LIMIT 150')}}
const route=path.match(/^\/api\/tenants\/([^/]+)(?:\/(.*))?$/);must(route,'Not found.',404);const tenantId=route[1],tail=route[2]||'',auth=await access(req,env,tenantId),tenant=auth.tenant;const requireRole=permission=>access(req,env,tenantId,permission);
if(tail==='sales'){await requireRole('admin');if(method==='GET'){const row=await one(env,'SELECT * FROM sales WHERE tenant_id=?',tenantId);return {data:row?JSON.parse(row.data):{stage:'Prospect',amount:750},version:row?.version||0}}if(method==='PUT'){const v=await body(req),d=salesData(v.data);const result=await run(env,'INSERT INTO sales (tenant_id,data,version,updated_at) SELECT ?,?,1,? WHERE ?=0 ON CONFLICT(tenant_id) DO NOTHING',tenantId,JSON.stringify(d),now(),v.version);if(!result.meta.changes){const updated=await run(env,'UPDATE sales SET data=?,version=version+1,updated_at=? WHERE tenant_id=? AND version=?',JSON.stringify(d),now(),tenantId,v.version);must(updated.meta.changes,'Sales record changed. Reopen it before saving.',409)}await log(env,user,tenantId,'sales.updated',d.stage+' · manually recorded');return {ok:true}}}
if(tail==='readiness'&&method==='GET'){return {checks:readiness(JSON.parse(tenant.settings),await all(env,'SELECT id FROM photos WHERE tenant_id=?',tenantId),await all(env,'SELECT published FROM projects WHERE tenant_id=?',tenantId))}}
if(tail==='render'&&method==='POST'){await requireRole('write');const v=await body(req),s=settings(v.settings),photos=await all(env,'SELECT id,project_id,caption,stage FROM photos WHERE tenant_id=?',tenantId);for(const key of ['logoId','ownerPhotoId','heroPhotoId'])if(s[key])must(photos.some(p=>p.id===s[key]&&!p.project_id),'Choose this website’s brand image.');const projects=await all(env,'SELECT * FROM projects WHERE tenant_id=? ORDER BY created_at DESC',tenantId);return {html:sitePage({...tenant,settings:JSON.stringify(s)},demoProjects({...tenant,settings:JSON.stringify(s)},projects,true),photos,{preview:true})}}
if(!tail&&method==='GET'){return {tenant:tenantView(tenant),role:auth.role,projects:(await all(env,'SELECT * FROM projects WHERE tenant_id=? ORDER BY updated_at DESC',tenantId)).map(p=>({...p,data:JSON.parse(p.data),published:p.published?JSON.parse(p.published):null})),photos:await all(env,'SELECT id,project_id,caption,stage,bytes,created_at FROM photos WHERE tenant_id=?',tenantId),inquiries:await all(env,'SELECT * FROM inquiries WHERE tenant_id=? ORDER BY created_at DESC LIMIT 150',tenantId)}}
if(!tail&&method==='PUT'){await requireRole('write');const v=await body(req),s=settings(v.settings);await validateSavedDesign(env,s);for(const key of ['logoId','ownerPhotoId','heroPhotoId'])if(s[key])must(await one(env,'SELECT id FROM photos WHERE id=? AND tenant_id=? AND project_id IS NULL',s[key],tenantId),'Select an image belonging to this website.');const result=await run(env,'UPDATE tenants SET settings=?,name=?,version=version+1,updated_at=? WHERE id=? AND version=?',JSON.stringify(s),s.name,now(),tenantId,v.version);must(result.meta.changes,'This website changed in another tab. Reload before saving.',409);await recordDesignUse(env,s,tenantId);await log(env,user,tenantId,'settings.saved');return {tenant:tenantView(await one(env,'SELECT * FROM tenants WHERE id=?',tenantId))}}
if(tail==='publish'&&method==='POST'){await requireRole('owner');const v=await body(req),s=JSON.parse(tenant.settings);must(v.version===tenant.version,'Reload the latest website before publishing.',409);must(s.phone.replace(/\D/g,'').length>=10&&s.area&&s.hero&&s.services.length,'Add a phone, service area, headline, and at least one service.');must(v.approved===true,'Confirm you reviewed the business facts before publishing.');await snapshot(env,user,tenant,'Before website publish');const result=await run(env,"UPDATE tenants SET published=settings,status='published',version=version+1,updated_at=? WHERE id=? AND version=?",now(),tenantId,v.version);must(result.meta.changes,'Website changed during publishing. Reload and retry.',409);await log(env,user,tenantId,'website.published');return {ok:true,url:'/s/'+tenant.slug}}
if(tail==='unpublish'&&method==='POST'){await requireRole('owner');await run(env,"UPDATE tenants SET status='draft',published=NULL,version=version+1,updated_at=? WHERE id=?",now(),tenantId);await log(env,user,tenantId,'website.unpublished');return {ok:true}}
if(tail==='duplicate'&&method==='POST'){await requireRole('admin');const v=await body(req),slug=text(v.slug,60),name=text(v.name,250);must(/^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/.test(slug)&&name.length>1,'Enter a business name and unique lowercase URL name.');must(!await one(env,'SELECT id FROM tenants WHERE slug=?',slug),'URL name already used.',409);const original=JSON.parse(tenant.settings),s={...DEFAULT,name,trade:original.trade,template:original.template,color:original.color,designKit:original.designKit||'',design:original.design,effects:original.effects,savedDesignId:original.savedDesignId||'',sections:original.sections||[],showOwner:original.showOwner,showOwnerPhoto:original.showOwnerPhoto,showProjects:original.showProjects,hero:DEFAULT.hero,services:original.services.map(x=>({name:x.name,description:''}))};const id=uid(),t=now();await run(env,'INSERT INTO tenants (id,slug,name,settings,created_at,updated_at) VALUES (?,?,?,?,?,?)',id,slug,name,JSON.stringify(s),t,t);await validateSavedDesign(env,s);await recordDesignUse(env,s,id);await log(env,user,id,'website.duplicated','Copied layout and service names; no contacts, photos, projects, or access copied.');return {id}}
if(tail==='projects'&&method==='POST'){await requireRole('write');const v=projectData(await body(req)),id=uid(),t=now();must(!v.beforeId&&!v.afterId&&!v.coverId&&!v.photoOrder.length,'Create the project before adding photographs.');await run(env,'INSERT INTO projects (id,tenant_id,data,created_at,updated_at) VALUES (?,?,?,?,?)',id,tenantId,JSON.stringify(v),t,t);await log(env,user,tenantId,'project.created',v.title);return {id}}
const pr=tail.match(/^projects\/([^/]+)(?:\/(publish|unpublish))?$/);if(pr){await requireRole(pr[2]?'owner':'write');const p=await one(env,'SELECT * FROM projects WHERE id=? AND tenant_id=?',pr[1],tenantId);must(p,'Project not found.',404);if(method==='PUT'&&!pr[2]){const v=await body(req),d=projectData(v.data);for(const [key,stage]of [['beforeId','before'],['afterId','after']])if(d[key])must(await one(env,'SELECT id FROM photos WHERE id=? AND tenant_id=? AND project_id=? AND stage=?',d[key],tenantId,p.id,stage),'Select the correct comparison photo from this project.');for(const id of [...d.photoOrder,...(d.coverId?[d.coverId]:[])])must(await one(env,'SELECT id FROM photos WHERE id=? AND tenant_id=? AND project_id=?',id,tenantId,p.id),'Choose photos from this project.');const result=await run(env,'UPDATE projects SET data=?,version=version+1,updated_at=? WHERE id=? AND tenant_id=? AND version=?',JSON.stringify(d),now(),p.id,tenantId,v.version);must(result.meta.changes,'Project changed. Reload before saving.',409);await log(env,user,tenantId,'project.saved',d.title);return {ok:true}}if(pr[2]==='publish'&&method==='POST'){const v=await body(req);must(v.version===p.version,'Project changed. Reload before publishing.',409);const d=JSON.parse(p.data);must(d.approved&&d.problem.length>=20&&d.work.length>=20&&d.outcome.length>=20,'Confirm photo permission and add the problem, work, and outcome (20+ characters each).');for(const [key,stage]of [['beforeId','before'],['afterId','after']])must(await one(env,'SELECT id FROM photos WHERE id=? AND tenant_id=? AND project_id=? AND stage=?',d[key],tenantId,p.id,stage),'Choose a before and after photo.');for(const id of [...(d.photoOrder||[]),...(d.coverId?[d.coverId]:[])])must(await one(env,'SELECT id FROM photos WHERE id=? AND tenant_id=? AND project_id=?',id,tenantId,p.id),'Choose photos from this project.');d.photoIds=(await all(env,'SELECT id FROM photos WHERE tenant_id=? AND project_id=?',tenantId,p.id)).map(x=>x.id);await snapshot(env,user,tenant,'Before project publish');const result=await run(env,'UPDATE projects SET published=?,version=version+1,updated_at=? WHERE id=? AND tenant_id=? AND version=?',JSON.stringify(d),now(),p.id,tenantId,v.version);must(result.meta.changes,'Project changed during publishing.',409);await log(env,user,tenantId,'project.published',d.title);return {ok:true}}if(pr[2]==='unpublish'&&method==='POST'){await run(env,'UPDATE projects SET published=NULL,version=version+1,updated_at=? WHERE id=? AND tenant_id=?',now(),p.id,tenantId);await log(env,user,tenantId,'project.unpublished');return {ok:true}}}
if(tail==='photos'&&method==='POST'){await requireRole('write');must(env.BUCKET,'Photo storage unavailable.',503);const count=await one(env,'SELECT COUNT(*) AS n FROM photos WHERE tenant_id=?',tenantId);must(count.n<60,'This release supports up to 60 photos per website.');const projectId=url.searchParams.get('projectId')||null,stage=url.searchParams.get('stage')||'brand';if(projectId){must(await one(env,'SELECT id FROM projects WHERE id=? AND tenant_id=?',projectId,tenantId),'Project not found.',404);must(['before','during','after'].includes(stage),'Choose the photo stage.')}else must(stage==='brand','Choose a brand image.');const data=jpeg(await bytes(req,2*1024*1024)),id=uid(),key=`photos/${tenantId}/${id}.jpg`;await env.BUCKET.put(key,data,{httpMetadata:{contentType:'image/jpeg'}});try{await run(env,'INSERT INTO photos (id,tenant_id,project_id,object_key,caption,stage,bytes,created_at) VALUES (?,?,?,?,?,?,?,?)',id,tenantId,projectId,key,text(url.searchParams.get('caption'),300),stage,data.length,now())}catch(error){await env.BUCKET.delete(key);throw error}await log(env,user,tenantId,'photo.uploaded',stage);return {id,url:'/media/'+id}}
if(tail==='access'&&method==='GET'){await requireRole('owner');return {members:await all(env,'SELECT * FROM members WHERE tenant_id=?',tenantId),invites:await all(env,'SELECT id,email,role,expires_at,used_at,revoked,created_at FROM invites WHERE tenant_id=? ORDER BY created_at DESC',tenantId)}}
if(tail==='invites'&&method==='POST'){await requireRole('owner');const v=await body(req),email=text(v.email,250).toLowerCase(),role=v.role;must(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email),'Enter a valid email.');must(['owner','editor','viewer'].includes(role),'Choose an access role.');const token=uid()+uid(),id=uid();await run(env,'INSERT INTO invites (id,tenant_id,email,role,token_hash,expires_at,created_at) VALUES (?,?,?,?,?,?,?)',id,tenantId,email,role,await hash(token),new Date(Date.now()+7*86400000).toISOString(),now());await log(env,user,tenantId,'invitation.created',role);return {url:'/join#'+token,id}}
const revoke=tail.match(/^(members|invites)\/([^/]+)\/revoke$/);if(revoke&&method==='POST'){await requireRole('owner');if(revoke[1]==='members'){const m=await one(env,'SELECT * FROM members WHERE id=? AND tenant_id=?',revoke[2],tenantId);must(m,'Member not found.',404);must(m.user_id!==user.id,'Ask Buildovate to revoke your own access.');await run(env,'UPDATE members SET active=0 WHERE id=? AND tenant_id=?',m.id,tenantId)}else await run(env,'UPDATE invites SET revoked=1 WHERE id=? AND tenant_id=?',revoke[2],tenantId);await log(env,user,tenantId,'access.revoked');return {ok:true}}
if(tail==='backups'){await requireRole('owner');if(method==='POST')return {id:await snapshot(env,user,tenant,'Manual backup')};return {backups:await all(env,'SELECT id,reason,bytes,checksum,created_at FROM backups WHERE tenant_id=? ORDER BY created_at DESC',tenantId)}}
const br=tail.match(/^backups\/([^/]+)\/(download|restore)$/);if(br){await requireRole('owner');if(br[2]==='restore'&&method==='POST'){const v=await body(req);must(v.confirm===true,'Confirm restore.');return restore(env,user,tenant,br[1],v.version)}if(br[2]==='download'&&method==='GET'){const {raw}=await backupContent(env,tenantId,br[1]);return new Response(raw,{headers:{'content-type':'application/json','content-disposition':'attachment; filename="buildovate-backup.json"','cache-control':'no-store'}})}}
if(tail==='domains'){await requireRole('owner');if(method==='GET')return {domains:await all(env,'SELECT * FROM domains WHERE tenant_id=? ORDER BY created_at DESC',tenantId)};if(method==='POST'){const v=await body(req),hostname=text(v.hostname,250).toLowerCase();must(/^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/.test(hostname),'Enter a domain only, such as www.example.com.');must(!await one(env,'SELECT id FROM domains WHERE hostname=?',hostname),'Domain already registered in this platform.',409);const id=uid();await run(env,'INSERT INTO domains (id,tenant_id,hostname,token,created_at) VALUES (?,?,?,?,?)',id,tenantId,hostname,'buildovate-'+uid(),now());await log(env,user,tenantId,'domain.requested',hostname);return {ok:true}}}
const dr=tail.match(/^domains\/([^/]+)\/verify$/);if(dr&&method==='POST'){await requireRole('owner');const d=await one(env,'SELECT * FROM domains WHERE id=? AND tenant_id=?',dr[1],tenantId);must(d,'Domain not found.',404);const r=await fetch('https://cloudflare-dns.com/dns-query?name='+encodeURIComponent('_buildovate.'+d.hostname)+'&type=TXT',{headers:{accept:'application/dns-json'},signal:AbortSignal.timeout(8000)});must(r.ok,'DNS lookup unavailable. Try again later.',503);const data=await r.json();const verified=data.Status===0&&(data.Answer||[]).some(a=>a.type===16&&a.data.replace(/"/g,'')===d.token);await run(env,'UPDATE domains SET ownership=?,checked_at=? WHERE id=? AND tenant_id=?',verified?'verified':'pending',now(),d.id,tenantId);await log(env,user,tenantId,'domain.checked',verified?'Ownership verified; hosting not connected':'TXT record not found');return {verified}}
throw new Fault('Not found.',404);
}
