import {cleanDesign} from './design-variant.js';
import {cleanPricing} from './pricing.js';
import {cleanReviews} from './reviews.js';
import {kits,effectKeys} from './design-kits.js';
import tradeLibrary from '../public/trade-library.json' with {type:'json'};
import {sections} from './builder.js';
export const uid=()=>crypto.randomUUID();
export const now=()=>new Date().toISOString();
export const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const text=(v,max=3000)=>typeof v==='string'?v.trim().slice(0,max):'';
export class Fault extends Error{constructor(message,status=400){super(message);this.status=status}}
export const must=(condition,message,status=400)=>{if(!condition)throw new Fault(message,status)};
export const db=env=>{must(env.DB,'Database unavailable. Please retry.',503);return env.DB};
export const one=(env,sql,...args)=>db(env).prepare(sql).bind(...args).first();
export const all=async(env,sql,...args)=>(await db(env).prepare(sql).bind(...args).all()).results;
export const run=(env,sql,...args)=>db(env).prepare(sql).bind(...args).run();
export async function hash(value){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',typeof value==='string'?new TextEncoder().encode(value):value))].map(v=>v.toString(16).padStart(2,'0')).join('')}
export async function bytes(req,limit){const reader=req.body?.getReader();must(reader,'Request body required.');let chunks=[],size=0;while(true){const v=await reader.read();if(v.done)break;size+=v.value.length;if(size>limit){await reader.cancel();throw new Fault('Upload exceeds the size limit.',413)}chunks.push(v.value)}const result=new Uint8Array(size);let off=0;for(const c of chunks){result.set(c,off);off+=c.length}return result}
export async function body(req){try{return JSON.parse(new TextDecoder().decode(await bytes(req,90000)))}catch(error){if(error instanceof Fault)throw error;throw new Fault('Could not read the form.')}}
export const person=req=>{const id=req.headers.get('oai-authenticated-user-id'),email=req.headers.get('oai-authenticated-user-email');return id?{id,email:(email||'').toLowerCase()}:null};
export async function identity(req,env){const p=person(req);must(p,'Sign in to continue.',401);const row=await one(env,'SELECT role FROM admins WHERE user_id=?',p.id);return {...p,admin:row?.role==='admin',staff:!!row,platformRole:row?.role||null}}
export async function access(req,env,tenantId,permission='read'){const user=await identity(req,env),tenant=await one(env,'SELECT * FROM tenants WHERE id=?',tenantId);must(tenant,'Website not found.',404);let role='admin';if(!user.admin){const m=await one(env,'SELECT role FROM members WHERE tenant_id=? AND user_id=? AND active=1',tenantId,user.id);must(m,'Website not found.',404);role=m.role}if(permission==='write')must(['admin','owner','editor'].includes(role),'Your role has read-only access.',403);if(permission==='owner')must(['admin','owner'].includes(role),'Owner access required.',403);if(permission==='admin')must(user.admin,'Buildovate administrator access required.',403);return {user,tenant,role}}
export const log=(env,user,tenant,action,detail='')=>run(env,'INSERT INTO audit (id,tenant_id,actor,action,detail,created_at) VALUES (?,?,?,?,?,?)',uid(),tenant,user.email||user.id,action,text(detail,500),now());
export const TRADES=Object.keys(tradeLibrary);
export const DEFAULT={name:'',trade:'Roofing',owner:'',phone:'',email:'',address:'',hours:'',license:'',experience:'',area:'',hero:'Built with care. Made to last.',intro:'',color:'#cd754a',template:'craft',showOwner:true,showProjects:true,logoId:null,ownerPhotoId:null,services:[]};
export const ROBLES={...DEFAULT,name:'Robles Roofing',owner:'Mario Robles Jr.',phone:'(805) 248-0739',email:'mariorobles366@gmail.com',address:'420 Hazelwood Dr, Oxnard, CA 93030',hours:'Monday–Saturday, 7:00 AM–5:00 PM',license:'#1053713',experience:'30+ years',area:'Oxnard and Ventura County',hero:'Roofs built for California.',intro:'Roof repair, installation, and maintenance for residential and commercial properties.',services:['Roof installation','Roof repair','Roof maintenance','Asphalt shingle install / repair','Metal roofing','Flat roofs','Roof sealing','Gutters','Storm damage','Inspections','Roof replacement'].map(name=>({name,description:''}))};
export function settings(input){const out={};for(const key of ['name','trade','owner','phone','email','address','hours','license','experience','area','hero','intro','color','template','seoTitle','seoDescription','ctaLabel'])out[key]=text(input[key],key==='intro'?1500:250);must(out.name.length>=2,'Enter a business name.');if(out.trade==='General contracting')out.trade='General Contractors';must(TRADES.includes(out.trade),'Choose a trade.');must(/^#[0-9a-f]{6}$/i.test(out.color),'Choose a valid brand color.');must(['craft','clean','editorial','blueprint','cinematic'].includes(out.template),'Choose a template style.');must(!out.email||/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(out.email),'Enter a valid email.');for(const k of ['showOwner','showProjects','showOwnerPhoto','showDemoProjects'])out[k]=input[k]!==false;for(const k of ['logoId','ownerPhotoId','heroPhotoId'])out[k]=text(input[k],80)||null;out.savedDesignId=text(input.savedDesignId,80);out.design=cleanDesign(input.design);out.reviews=cleanReviews(input.reviews);out.pricing=cleanPricing(input.pricing,out.trade);out.designKit=kits[input.designKit]&&kits[input.designKit].trade===out.trade?input.designKit:'';out.creativeBrief=text(input.creativeBrief,12000);out.effects=Object.fromEntries(effectKeys.map(k=>[k,input.effects?.[k]!==false]));out.sections=sections(input.sections);out.claimsReviewed=input.claimsReviewed===true;out.services=(Array.isArray(input.services)?input.services:[]).slice(0,24).map(s=>({name:text(s.name,100),description:text(s.description,600)})).filter(s=>s.name);return out}
export const tenantView=t=>({...t,settings:JSON.parse(t.settings),published:t.published?JSON.parse(t.published):null});
export function projectData(v){const out={};for(const k of ['title','city','service','material','concern','property','completedAt','problem','findings','recommendation','work','outcome','summary','size','duration','scope','materialDetails','beforeId','afterId','coverId'])out[k]=text(v[k],['problem','findings','recommendation','work','outcome','scope','materialDetails'].includes(k)?5000:k==='summary'?500:200);must(out.title.length>=3,'Enter a project title.');must(out.city,'Enter a city.');out.lat=Number(v.lat);out.lng=Number(v.lng);must(Number.isFinite(out.lat)&&Math.abs(out.lat)<=90&&Number.isFinite(out.lng)&&Math.abs(out.lng)<=180,'Enter valid approximate city coordinates.');must(/^\d{4}-\d{2}-\d{2}$/.test(out.completedAt)&&Number.isFinite(Date.parse(out.completedAt))&&new Date(out.completedAt).toISOString().slice(0,10)===out.completedAt&&out.completedAt<=now().slice(0,10),'Choose a valid completion date, today or earlier.');out.photoOrder=(Array.isArray(v.photoOrder)?v.photoOrder:[]).filter(x=>typeof x==='string').slice(0,60);out.approved=v.approved===true;return out}
export function jpeg(data){must(data.length>4&&data[0]===255&&data[1]===216&&data.at(-2)===255&&data.at(-1)===217,'Use a valid JPEG photo.');let p=2,out=[data.slice(0,2)],scan=false;while(p<data.length){must(data[p]===255,'Invalid JPEG photo.');const m=data[p+1];if(m===218){out.push(data.slice(p));scan=true;break}const len=(data[p+2]<<8)|data[p+3];must(len>=2&&p+len+2<=data.length,'Invalid JPEG photo.');if(!(m>=224&&m<=239)&&m!==254)out.push(data.slice(p,p+len+2));p+=len+2}must(scan,'Invalid JPEG photo.');const result=new Uint8Array(out.reduce((n,x)=>n+x.length,0));let i=0;for(const x of out){result.set(x,i);i+=x.length}return result}
