import {rebuildFollowups} from './control.js';
import {zoomStatus} from './zoom.js';
import {uid,now,text,must,one,all,run,db,body,identity,access,log,TRADES} from './core.js';
import {clean} from './workspace.js';
import {cleanFields,fieldAnswers} from './form-fields.js';
const decode=r=>({...r,data:JSON.parse(r.data)});
export const contactRows=async(env,scope)=>(await all(env,"SELECT * FROM workspace_records WHERE scope=? AND kind IN ('leads','contacts') ORDER BY updated_at DESC",scope)).map(decode);
const phone=v=>{let p=text(v,40).replace(/\D/g,'');return p.length===11&&p[0]==='1'?p.slice(1):p};
const key=v=>text(v,300).toLowerCase().replace(/[^a-z0-9]/g,'');
export function duplicate(a,b){return !!(((key(a.company)||key(a.name))&&['company','name','city','email','phone'].every(k=>key(a[k])===key(b[k])))||(a.email&&b.email&&a.email.toLowerCase()===b.email.toLowerCase())||(phone(a.phone)&&phone(a.phone)===phone(b.phone))||(key(a.company)&&key(a.city)&&key(a.company)===key(b.company)&&key(a.city)===key(b.city)))}
export async function crmMembers(env,scope){return scope==='global'?await all(env,"SELECT a.user_id,a.email,a.role,json_extract(p.data,'$.displayName') AS displayName,json_extract(p.data,'$.photoKey') IS NOT NULL AS hasPhoto FROM admins a LEFT JOIN workspace_records p ON p.id='profile-'||a.user_id AND p.kind='profile' ORDER BY a.email"):await all(env,'SELECT user_id,email,role FROM members WHERE tenant_id=? AND active=1 ORDER BY email',scope)}
export async function assignees(env,scope,v){const chosen=[...new Set((Array.isArray(v)?v:String(v||'').split(',')).map(x=>text(x,250).toLowerCase()).filter(Boolean))];const allowed=(await crmMembers(env,scope)).map(x=>x.email);must(chosen.length<=15&&chosen.every(x=>allowed.includes(x)),'Choose active members from this workspace.');return chosen}
export async function crmConfig(env,scope){const r=await one(env,"SELECT * FROM workspace_records WHERE scope=? AND kind='crm_settings'",scope);return r?decode(r):{version:0,data:{columns:[],calendarFields:[]}}}
export async function crmNext(req,env,url){const match=url.pathname.match(/^\/api\/(?:crm\/([^/]+)\/([^/]+)|workspace\/([^/]+)\/(contacts|leads)(?:\/([^/]+))?(?:\/([^/]+))?)$/);if(!match)return null;const scope=match[1]||match[3],op=match[2],id=match[5],action=match[6],method=req.method,user=await identity(req,env);if(scope==='global')must(user.staff,'Staff access required.',403);else await access(req,env,scope,method==='GET'?'read':'write');if(method!=='GET')must(req.headers.get('origin')===url.origin,'Invalid origin.',403);
if(op==='zoom'&&method==='GET')return scope==='global'?zoomStatus(env):{configured:false,host:'',message:'This contractor workspace does not have a Zoom account connected.'};
if(op==='members'&&method==='GET')return {members:await crmMembers(env,scope)};
if(op==='settings'){const old=await crmConfig(env,scope);if(method==='GET')return old;must(method==='PUT','Method not supported.',405);if(scope==='global')must(user.admin,'Admin access required to configure workspace fields.',403);else await access(req,env,scope,'owner');const v=await body(req);must(v.version===old.version,'Settings changed. Reopen them.',409);const d={tabs:Array.isArray(v.data.tabs)?v.data.tabs.slice(0,20).map(t=>({id:text(t.id,80)||uid(),label:text(t.label,80),trade:text(t.trade,100),specialty:text(t.specialty,150)})):old.data.tabs,columns:(v.data.columns||[]).slice(0,45).map(x=>({key:text(x.key,70),label:text(x.label,70),visible:x.visible!==false})),calendarFields:cleanFields(v.data.calendarFields||[])};must(!d.tabs||d.tabs.every(t=>t.label),'Name every contact tab.');must(d.columns.every(x=>x.key&&x.label&&!['__proto__','prototype','constructor'].includes(x.key))&&new Set(d.columns.map(x=>x.key)).size===d.columns.length,'Use unique, named columns.');const t=now();if(old.version){const r=await run(env,'UPDATE workspace_records SET data=?,version=version+1,updated_at=? WHERE id=? AND version=?',JSON.stringify(d),t,old.id,old.version);must(r.meta.changes,'Settings changed.',409)}else await run(env,"INSERT INTO workspace_records(id,scope,kind,data,created_at,updated_at) VALUES(?,?,'crm_settings',?,?,?)",'crm-settings-'+scope,scope,JSON.stringify(d),t,t);await log(env,user,scope==='global'?null:scope,'crm.settings.updated');return {ok:true}}
if(op==='demo'){must(method==='POST'&&scope==='global'&&user.admin,'Admin access required.',403);const input=await body(req);if(input.once&&await one(env,"SELECT id FROM workspace_records WHERE id='crm-demo-seeded' AND scope='global'"))return {added:0};const records=await contactRows(env,scope);let added=0;for(let i=0;i<TRADES.length;i++){const d=clean('contacts',{company:'Demo · '+TRADES[i]+' Studio',name:'Demo Contact '+(i+1),trade:TRADES[i],city:'Oxnard',email:'demo-'+i+'@example.test',phone:'202-555-01'+String(i).padStart(2,'0'),stage:['New','Called','Booked','Built','Shown','Paid','Lost'][i],tags:'DEMO · testing only',notes:'Fictional test contact. Do not contact.',assignedTo:user.email});d.assignees=[user.email];d.demo=true;d.program=i===5?'Growth':'';if(records.some(r=>duplicate(r.data,d)))continue;const t=now();const result=await run(env,"INSERT OR IGNORE INTO workspace_records(id,scope,kind,data,created_at,updated_at) VALUES(?,'global','contacts',?,?,?)",'demo-contact-'+i,JSON.stringify(d),t,t);added+=result.meta.changes}const t=now();await run(env,"INSERT OR IGNORE INTO workspace_records(id,scope,kind,data,created_at,updated_at) VALUES('crm-demo-seeded','global','seed_marker','{}',?,?)",t,t);return {added}}
if(op)must(false,'Not found.',404);
const records=await contactRows(env,scope),old=records.find(r=>r.id===id);if(method==='GET'){if(id){must(old,'Contact not found.',404);return {record:old}}return {records}}
if(method==='DELETE'){must(old,'Contact not found.',404);const v=await body(req);const r=await run(env,"DELETE FROM workspace_records WHERE id=? AND scope=? AND version=? AND kind IN ('contacts','leads')",id,scope,v.version);must(r.meta.changes,'Contact changed. Reopen before deleting.',409);await log(env,user,scope==='global'?null:scope,'contact.deleted',id);if(scope==='global')await rebuildFollowups(env);return {ok:true}}
if(['no-answer','call-outcome'].includes(action)&&method==='POST'){must(old,'Contact not found.',404);const v=await body(req);must(v.version===old.version,'Contact changed. Reopen it.',409);const outcome=action==='no-answer'?'No Answer':text(v.outcome,30);must(['No Answer','Voicemail','Connected','Not interested'].includes(outcome),'Choose a call outcome.');const t=now(),data={...old.data,callAttempts:(Number(old.data.callAttempts)||0)+1,lastCallAt:t,callOutcome:outcome,lastActivity:outcome+' · '+t,stage:old.data.stage==='New'?'Called':old.data.stage,calls:[...(old.data.calls||[]),{at:t,outcome,by:user.email}].slice(-300)};const r=await run(env,'UPDATE workspace_records SET data=?,version=version+1,updated_at=? WHERE id=? AND scope=? AND version=?',JSON.stringify(data),t,id,scope,old.version);must(r.meta.changes,'Contact changed; call was not recorded twice.',409);await log(env,user,scope==='global'?null:scope,'contact.no_answer',id);return {ok:true}}
must(['POST','PUT'].includes(method),'Method not supported.',405);const v=await body(req);const importing=id==='import'&&method==='POST';if(!importing&&id)must(old&&v.version===old.version,'Contact changed or not found. Reopen it.',409);const inputs=importing?v.rows:[v.data||v];must(Array.isArray(inputs)&&inputs.length>0&&inputs.length<=250,'Import 1–250 rows.');let skipped=0;const prepared=[];for(const raw of inputs){const d=clean('contacts',raw);d.assignees=await assignees(env,scope,raw.assignees||raw.assignedTo);d.assignedTo=d.assignees.join(', ');for(const k of ['appointmentEmailConsent','appointmentSmsConsent','marketingEmailConsent','marketingSmsConsent','optedOut'])d[k]=raw[k]===true;d.consentNote=text(raw.consentNote,1000);must(!(d.marketingEmailConsent||d.marketingSmsConsent)||d.consentNote.length>2,'Record the source and date of promotional permission.');d.consentUpdatedAt=now();d.program=text(raw.program,100);d.upsell=text(raw.upsell,100);d.dealValue=Number(raw.dealValue||0);must(Number.isFinite(d.dealValue)&&d.dealValue>=0&&d.dealValue<=1000000,'Enter a valid deal value.');if(duplicateIn(d)){if(importing){skipped++;continue}must(false,'Duplicate contact: matching email, phone, or company and city already exists.',409)}if(old)for(const k of ['demo','calls','callAttempts','lastCallAt','stageHistory'])d[k]=old.data[k];if(old&&old.data.stage!==d.stage)d.stageHistory=[...(old.data.stageHistory||[]),{from:old.data.stage,to:d.stage,at:now(),by:user.email}].slice(-100);if(d.stage==='Paid'&&old?.data.stage!=='Paid')d.wonAt=now();else d.wonAt=old?.data.wonAt||'';prepared.push(d)}
function duplicateIn(d){return records.some(r=>r.id!==old?.id&&duplicate(r.data,d))||prepared.some(x=>duplicate(x,d))}
must(records.length+prepared.length-(old?1:0)<=1000,'Contact limit reached (1,000).');let imported=0;const sum=records.reduce((s,r)=>s+r.version,0),t=now();for(const d of prepared){const guard="(SELECT COALESCE(SUM(version),0) FROM workspace_records WHERE scope=? AND kind IN ('contacts','leads'))=?";if(old){const r=await run(env,'UPDATE workspace_records SET data=?,version=version+1,updated_at=? WHERE id=? AND scope=? AND version=? AND '+guard,JSON.stringify(d),t,old.id,scope,old.version,scope,sum);must(r.meta.changes,'Contacts changed concurrently. Reopen and retry.',409);imported++}else{const r=await run(env,"INSERT INTO workspace_records(id,scope,kind,data,created_at,updated_at) SELECT ?,?,'contacts',?,?,? WHERE "+guard,uid(),scope,JSON.stringify(d),t,t,scope,sum+imported);must(r.meta.changes,'Contacts changed during import. Retry; already imported rows will be skipped.',409);imported++}}
await log(env,user,scope==='global'?null:scope,importing?'contacts.imported':old?'contact.updated':'contact.created',String(imported));if(scope==='global')await rebuildFollowups(env);return {ok:true,imported,skipped,id:old?.id||(await contactRows(env,scope)).find(r=>prepared[0]&&duplicate(r.data,prepared[0]))?.id};}
