import {all,one,run,db,uid,now,hash,must,log,Fault} from './core.js';
export async function snapshot(env,user,tenant,reason){must(env.BUCKET,'Backup storage unavailable.',503);const id=uid(),photos=await all(env,'SELECT * FROM photos WHERE tenant_id=?',tenant.id);const media=[];for(const p of photos){const file=await env.BUCKET.get(p.object_key);must(file,'A photo could not be backed up. No backup was marked complete.',503);const key=`backups/${tenant.id}/${id}/media/${p.id}.jpg`;await env.BUCKET.put(key,file.body,{httpMetadata:{contentType:'image/jpeg'}});media.push({...p,object_key:key})}const data={format:1,tenantId:tenant.id,createdAt:now(),settings:JSON.parse(tenant.settings),projects:await all(env,'SELECT * FROM projects WHERE tenant_id=?',tenant.id),photos:media,workspaceRecords:await all(env,"SELECT * FROM workspace_records WHERE scope=? AND kind<>'plan'",tenant.id),inquiries:await all(env,'SELECT * FROM inquiries WHERE tenant_id=?',tenant.id)};const raw=JSON.stringify(data),key=`backups/${tenant.id}/${id}/snapshot.json`,checksum=await hash(raw);await env.BUCKET.put(key,raw,{httpMetadata:{contentType:'application/json'}});await run(env,'INSERT INTO backups (id,tenant_id,object_key,reason,bytes,checksum,created_at) VALUES (?,?,?,?,?,?,?)',id,tenant.id,key,reason,new TextEncoder().encode(raw).length+photos.reduce((n,p)=>n+p.bytes,0),checksum,now());await log(env,user,tenant.id,'backup.created',reason);return id}
export async function backupContent(env,tenantId,id){const b=await one(env,'SELECT * FROM backups WHERE id=? AND tenant_id=?',id,tenantId);must(b,'Backup not found.',404);const file=await env.BUCKET.get(b.object_key);must(file,'Backup file unavailable.',503);const raw=await file.text();must(await hash(raw)===b.checksum,'Backup integrity check failed.',503);const data=JSON.parse(raw);must(data.tenantId===tenantId&&data.format===1,'Backup format mismatch.');return {data,raw,backup:b}}
export async function restore(env,user,tenant,id,version){
 const {data}=await backupContent(env,tenant.id,id);
 must(tenant.version===version,'Website changed. Reload before restoring.',409);
 for(const photo of data.photos)must(await env.BUCKET.head(photo.object_key),'A backed-up photo is unavailable. Restore stopped.',503);
 await snapshot(env,user,tenant,'Before restore');
 const t=now(),nonce=uid(),saved=JSON.stringify(data.settings),guard="EXISTS (SELECT 1 FROM tenants WHERE id=? AND json_extract(settings,'$._restore')=?)";
 const statements=[db(env).prepare("UPDATE tenants SET settings=?,name=?,published=NULL,status='draft',version=version+1,updated_at=? WHERE id=? AND version=?").bind(JSON.stringify({...data.settings,_restore:nonce}),data.settings.name,t,tenant.id,version),
 db(env).prepare('UPDATE projects SET published=NULL WHERE tenant_id=? AND '+guard).bind(tenant.id,tenant.id,nonce)];
 for(const p of data.projects)statements.push(db(env).prepare('INSERT INTO projects (id,tenant_id,data,published,version,created_at,updated_at) SELECT ?,?,?,NULL,1,?,? WHERE '+guard+' ON CONFLICT(id) DO UPDATE SET data=excluded.data,published=NULL,version=projects.version+1,updated_at=excluded.updated_at WHERE projects.tenant_id=excluded.tenant_id').bind(p.id,tenant.id,p.data,p.created_at,t,tenant.id,nonce));
 for(const p of data.photos)statements.push(db(env).prepare('INSERT INTO photos (id,tenant_id,project_id,object_key,caption,stage,bytes,created_at) SELECT ?,?,?,?,?,?,?,? WHERE '+guard+' ON CONFLICT(id) DO UPDATE SET object_key=excluded.object_key,caption=excluded.caption,stage=excluded.stage WHERE photos.tenant_id=excluded.tenant_id').bind(p.id,tenant.id,p.project_id,p.object_key,p.caption,p.stage,p.bytes,p.created_at,tenant.id,nonce));
 for(const r of (data.workspaceRecords||[]).filter(r=>['pages','forms','visibility','blog'].includes(r.kind)))statements.push(db(env).prepare('INSERT INTO workspace_records(id,scope,kind,data,published,version,created_at,updated_at) SELECT ?,?,?,?,NULL,1,?,? WHERE '+guard+' ON CONFLICT(id) DO UPDATE SET data=excluded.data,published=NULL,version=workspace_records.version+1,updated_at=excluded.updated_at WHERE workspace_records.scope=excluded.scope').bind(r.id,tenant.id,r.kind,r.data,r.created_at,t,tenant.id,nonce));
 statements.push(db(env).prepare("UPDATE tenants SET settings=? WHERE id=? AND json_extract(settings,'$._restore')=?").bind(saved,tenant.id,nonce));
 const result=await db(env).batch(statements);must(result[0].meta.changes,'Website changed. No restore was applied. Reload and retry.',409);
 await log(env,user,tenant.id,'backup.restored','Restored settings and projects as drafts; retained newer projects, inquiries and access.');return {ok:true};
}
export async function checkHealth(env){const started=Date.now(),result={database:{ok:false},storage:{ok:false},checkedAt:now(),kind:'Manual dependency check',externalUptime:'Not configured',scheduledBackups:'Not configured',domainProvider:'Not connected'};try{const t=Date.now();await one(env,'SELECT 1 AS ok');result.database={ok:true,ms:Date.now()-t}}catch{result.database={ok:false,error:'Database check failed'}}try{const t=Date.now(),key='health/'+uid();await env.BUCKET.put(key,'buildovate-health');const o=await env.BUCKET.get(key);must(o&&await o.text()==='buildovate-health','Storage check failed');await env.BUCKET.delete(key);result.storage={ok:true,ms:Date.now()-t}}catch{result.storage={ok:false,error:'Storage write/read check failed'}}result.durationMs=Date.now()-started;await run(env,'INSERT INTO health (id,data,created_at) VALUES (?,?,?)',uid(),JSON.stringify(result),now());return result}
