import {engagementApi} from './engagement.js';
import {pricingRoute} from './pricing.js';
import {controlApi} from './control.js';
import {crmNext} from './crm-next.js';
import {savedDesignsApi} from './saved-designs.js';
import {cleanDesign} from './design-variant.js';
import {reviewsApi} from './reviews.js';
import {showcasePage} from './showcase.js';
import {kits,kitDefaults,effectKeys} from './design-kits.js';
import specialties from '../public/trade-library.json' with {type:'json'};
import {DEFAULT,identity} from './core.js';
import {blogPage} from './blog.js';
import {crmApi,demoProjects,captureContact} from './crm.js';
import {workspaceApi,publicWorkspace,decorateWorkspace,previewPage} from './workspace.js';
import {api} from './api.js';
import {dashboard,sitePage} from './views.js';
import {Fault,must,uid,now,one,all,run,access,body,text,person} from './core.js';
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','cache-control':'no-store','x-content-type-options':'nosniff'}});
const html=(data,status=200)=>new Response(data,{status,headers:{'content-type':'text/html; charset=utf-8','cache-control':'private, no-store','x-robots-tag':'noindex, nofollow','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin'}});
export default {async fetch(req,env){const url=new URL(req.url);try{
const chat=await engagementApi(req,env,url);if(chat!==null)return chat instanceof Response?chat:json(chat);const pricing=await pricingRoute(req,env,url);if(pricing!==null)return typeof pricing==='string'?html(pricing):json(pricing);const control=await controlApi(req,env,url);if(control!==null)return control instanceof Response?control:json(control);const next=await crmNext(req,env,url);if(next!==null)return json(next);const saved=await savedDesignsApi(req,env,url);if(saved!==null)return json(saved);const reviewData=await reviewsApi(req,env,url);if(reviewData!==null)return json(reviewData);const design=url.pathname.match(/^\/design-preview\/([a-z-]+)\/(immersive|editorial|studio)$/);if(design){const user=await identity(req,env);if(!user.staff){must(url.searchParams.get('tenant'),'Choose an authorized website.',403);await access(req,env,url.searchParams.get('tenant'));}const kit=kits[design[1]];must(kit,'Design not found.',404);return html(showcasePage({...DEFAULT,...kitDefaults(kit.id,{name:'Your '+kit.trade+' Company',color:/^#[a-f0-9]{6}$/i.test(url.searchParams.get('color')||'')?url.searchParams.get('color'):kit.color,template:({immersive:'cinematic',editorial:'editorial',studio:'blueprint'})[design[2]],design:cleanDesign(Object.fromEntries(url.searchParams)),effects:Object.fromEntries(effectKeys.map(k=>[k,url.searchParams.get(k)!=='false'])),services:specialties[kit.trade].map(name=>({name,description:''}))})},{sample:true,preview:true}))}
const blog=await blogPage(req,env,url);if(blog!==null)return html(blog);const crm=await crmApi(req,env,url);if(crm!==null)return json(crm);const wp=await publicWorkspace(req,env,url);if(wp!==null)return typeof wp==='string'?html(wp):json(wp);const pv=url.pathname.match(/^\/preview\/([^/]+)$/);if(pv){const t=await one(env,'SELECT * FROM tenants WHERE slug=?',pv[1]);must(t,'Website not found.',404);await access(req,env,t.id);return html(previewPage(t.slug))}if(url.pathname.startsWith('/api/workspace/'))return json(await workspaceApi(req,env,url));
const lead=url.pathname.match(/^\/api\/public\/([^/]+)\/inquiries$/);if(lead&&req.method==='POST'){must(req.headers.get('origin')===url.origin,'Invalid request origin.',403);const tenant=await one(env,"SELECT * FROM tenants WHERE slug=? AND status='published' AND published IS NOT NULL",lead[1]);must(tenant,'Website not available.',404);const v=await body(req);if(v.website)return json({ok:true});const name=text(v.name,120),phone=text(v.phone,40).replace(/\D/g,''),message=text(v.message,3000),projectId=text(v.projectId,80)||null;must(name.length>=2&&phone.length>=10&&phone.length<=15&&v.consent===true,'Enter your name, phone, and contact permission.');if(projectId)must(await one(env,'SELECT id FROM projects WHERE id=? AND tenant_id=? AND published IS NOT NULL',projectId,tenant.id),'Project unavailable.',404);const n=await one(env,'SELECT COUNT(*) AS n FROM inquiries WHERE tenant_id=? AND phone=? AND created_at>?',tenant.id,phone,new Date(Date.now()-86400000).toISOString());must(n.n<3,'You have already sent several requests. Please call the business.',429);await run(env,'INSERT INTO inquiries (id,tenant_id,project_id,name,phone,message,created_at) VALUES (?,?,?,?,?,?,?)',uid(),tenant.id,projectId,name,phone,message,now());await captureContact(env,tenant.id,{name,phone,message});return json({ok:true})}
if(url.pathname.startsWith('/api/')){const result=await api(req,env,url);return result instanceof Response?result:json(result)}
if(url.pathname==='/'||url.pathname==='/join'||url.pathname==='/team-join')return html(dashboard());
if(url.pathname.startsWith('/media/')){const photo=await one(env,'SELECT * FROM photos WHERE id=?',url.pathname.slice(7));must(photo,'Photo not found.',404);const tenant=await one(env,'SELECT * FROM tenants WHERE id=?',photo.tenant_id);let allowed=false;if(tenant?.status==='published'&&tenant.published){const settings=JSON.parse(tenant.published);if([settings.logoId,settings.ownerPhotoId,settings.heroPhotoId].includes(photo.id))allowed=true;if(photo.project_id){const p=await one(env,'SELECT published FROM projects WHERE id=? AND tenant_id=?',photo.project_id,tenant.id);if(p?.published)allowed=JSON.parse(p.published).photoIds?.includes(photo.id)||false}}if(!allowed&&tenant?.status==='published'){allowed=!!await one(env,"SELECT id FROM workspace_records WHERE scope=? AND kind='blog' AND published IS NOT NULL AND json_extract(published,'$.coverPhotoId')=?",tenant.id,photo.id)}if(!allowed)await access(req,env,photo.tenant_id);const file=await env.BUCKET.get(photo.object_key);must(file,'Photo unavailable.',404);return new Response(file.body,{headers:{'content-type':'image/jpeg','cache-control':'private, no-store','x-content-type-options':'nosniff'}})}
const route=url.pathname.match(/^\/s\/([^/]+)(?:\/projects\/([^/]+))?\/?$/);if(route){const tenant=await one(env,'SELECT * FROM tenants WHERE slug=?',route[1]);must(tenant,'Website not found.',404);const preview=url.searchParams.get('preview')==='1';if(preview)await access(req,env,tenant.id);else must(tenant.status==='published'&&tenant.published,'This website is not published yet.',404);const projects=demoProjects(tenant,await all(env,'SELECT * FROM projects WHERE tenant_id=?'+(preview?'':' AND published IS NOT NULL')+' ORDER BY created_at DESC',tenant.id),preview);if(route[2])must(projects.some(p=>p.id===route[2]),'Project not found.',404);const photos=await all(env,'SELECT id,project_id,caption,stage FROM photos WHERE tenant_id=?',tenant.id);return html(await decorateWorkspace(env,tenant,sitePage(tenant,projects,photos,{preview,project:route[2]}),preview))}
if(url.pathname==='/robots.txt')return new Response('User-agent: *\nDisallow: /\n');if(env.ASSETS)return env.ASSETS.fetch(req);throw new Fault('Not found.',404);
}catch(error){const status=error instanceof Fault?error.status:503;if(status===503){console.error('Request failed',url.pathname,error);try{await run(env,'INSERT INTO audit (id,tenant_id,actor,action,detail,created_at) VALUES (?,NULL,?,?,?,?)',uid(),person(req)?.id||'anonymous','system.error',url.pathname,now())}catch{}}const message=error instanceof Fault?error.message:'Service temporarily unavailable. Your unsaved form has not been cleared; please retry.';return (url.pathname.startsWith('/api/')||req.method==='POST')?json({error:message},status):html('<!doctype html><html lang="en"><meta name="viewport" content="width=device-width"><title>Buildovate</title><link rel="stylesheet" href="/app.css"><main class="standalone"><h1>'+message+'</h1><a href="/">Back to workspace</a> · <a target="_top" href="/signin-with-chatgpt?return_to='+encodeURIComponent(url.pathname+url.search)+'">Sign in with ChatGPT</a></main></html>',status)}}};
