import {one,run,now,log} from './core.js';
export const zoomStatus=env=>({configured:!!(env.ZOOM_ACCOUNT_ID&&env.ZOOM_CLIENT_ID&&env.ZOOM_CLIENT_SECRET&&env.ZOOM_HOST_USER_ID),host:env.ZOOM_HOST_USER_ID||'',message:'Authorize a Zoom Server-to-Server OAuth app and configure its account ID, client ID, client secret and meeting host in the platform server settings.'});
export async function syncZoom(env,scope,id,user){if(scope!=='global')return {status:'not_connected'};const record=await one(env,"SELECT * FROM workspace_records WHERE scope=? AND kind='calendar' AND id=?",scope,id);if(!record)return {status:'unavailable'};const d=JSON.parse(record.data);if(d.meetingType!=='Zoom'||d.status!=='Scheduled')return {status:'not_requested'};
 const jobId='zoom-'+id;let job=await one(env,"SELECT * FROM workspace_records WHERE id=? AND scope='global' AND kind='zoom_meeting'",jobId);let state=job?JSON.parse(job.data):null;
 if(!state&&d.location)return {status:'manual',joinUrl:d.location};
 if(!zoomStatus(env).configured)return {status:'not_connected'};
 const signature=JSON.stringify([d.title,d.start,d.end,d.timezone]);if(state?.signature===signature&&state.status==='ready')return {status:'ready',joinUrl:state.joinUrl};
 if(['pending','uncertain'].includes(state?.status))return {status:state.status,message:'Check this appointment in Zoom before retrying; a request may already have created its meeting.'};
 const t=now(),pending={...state,status:'pending',signature};let locked;
 if(job)locked=await run(env,"UPDATE workspace_records SET data=?,version=version+1,updated_at=? WHERE id=? AND version=?",JSON.stringify(pending),t,jobId,job.version);
 else locked=await run(env,"INSERT OR IGNORE INTO workspace_records(id,scope,kind,data,created_at,updated_at) VALUES(?,'global','zoom_meeting',?,?,?)",jobId,JSON.stringify(pending),t,t);
 if(!locked.meta.changes)return {status:'pending'};
 let meetingRequested=false,definitiveFailure=false;
 try{const tokenResponse=await fetch('https://zoom.us/oauth/token',{method:'POST',headers:{authorization:'Basic '+btoa(env.ZOOM_CLIENT_ID+':'+env.ZOOM_CLIENT_SECRET),'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'account_credentials',account_id:env.ZOOM_ACCOUNT_ID}),signal:AbortSignal.timeout(15000)});if(!tokenResponse.ok)throw Error('Zoom authorization failed. Check the authorized app and credentials.');const token=await tokenResponse.json();if(!token.access_token)throw Error('Zoom did not return an access token.');
 const payload={topic:d.title,type:2,start_time:d.start,duration:Math.max(1,Math.ceil((Date.parse(d.end)-Date.parse(d.start))/60000)),timezone:d.timezone,settings:{waiting_room:true,join_before_host:false,approval_type:2}};
 meetingRequested=true;const response=await fetch(state?.meetingId?'https://api.zoom.us/v2/meetings/'+encodeURIComponent(state.meetingId):'https://api.zoom.us/v2/users/'+encodeURIComponent(env.ZOOM_HOST_USER_ID)+'/meetings',{method:state?.meetingId?'PATCH':'POST',headers:{authorization:'Bearer '+token.access_token,'content-type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(20000)});
 if(!response.ok){definitiveFailure=response.status<500;throw Error('Zoom could not create or update the meeting. Check host access and meeting permissions.')}const meeting=state?.meetingId?{id:state.meetingId,join_url:state.joinUrl}:await response.json();const u=new URL(meeting.join_url);if(u.protocol!=='https:'||!(u.hostname==='zoom.us'||u.hostname.endsWith('.zoom.us')||u.hostname==='zoom.com'||u.hostname.endsWith('.zoom.com')))throw Error('Zoom returned an invalid meeting URL.');
 const ready={status:'ready',signature,meetingId:String(meeting.id),joinUrl:u.href,host:env.ZOOM_HOST_USER_ID};await run(env,'UPDATE workspace_records SET data=?,version=version+1,updated_at=? WHERE id=?',JSON.stringify(ready),now(),jobId);await run(env,"UPDATE workspace_records SET data=json_set(data,'$.location',?),version=version+1,updated_at=? WHERE id=? AND scope='global' AND kind='calendar'",u.href,now(),id);await log(env,user,null,'zoom.meeting.ready',id);return {status:'ready',joinUrl:u.href};
 }catch(error){const status=meetingRequested&&!definitiveFailure?'uncertain':'failed';await run(env,'UPDATE workspace_records SET data=?,version=version+1,updated_at=? WHERE id=?',JSON.stringify({...pending,status,message:status==='uncertain'?'Zoom response was incomplete. Check Zoom before creating another meeting.':String(error.message).slice(0,200)}),now(),jobId);return {status,message:status==='uncertain'?'Check Zoom before retrying to avoid duplicate meetings.':'Zoom authorization or meeting creation failed; the appointment is saved.'}}
}
